### ISSUE TITLE
Different Size Tiff to Jpg

### ISSUE THREAD

**Issue by uihyeon22** [SixLabors/ImageSharp#2170] opened 2022-07-08 08:45 UTC
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have verified that I am running the latest version of ImageSharp
- [X] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [X] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### ImageSharp version

2.1.2

### Other ImageSharp packages and versions

-

### Environment (Operating system, version and so on)

Window 10 , Dokcer (Linux)

### .NET Framework version

net6.0

### Description

I want to explore whether there are multiple tiffs and a single tiff. However, when multiple Tiffs of different sizes are received, an Exception occurs in Load.

I want to confirm that there are multiple sheets and one sheet. What should I do? If you check the Closed Issue below, it says to load it with `FrameDecodingMode.First`, but isn't it always 1 sheet?.

https://github.com/SixLabors/ImageSharp/issues/2113

Test Tiff File Size = 250Mb
Test Tiff count = 900ea

The image was confirmed from the service in the link.
https://cloudconvert.com/tif-to-jpg

```
    public bool IsUnzipPassable(string imagePath)
    {
        using var loadImage = Image.Load(imagePath, new TiffDecoder()
        {
            DecodingMode = FrameDecodingMode.ALL
        });
        return loadImage.Frames.Count > 1;
    }
```

```
Error SixLabors.ImageSharp:Images with different sizes are not supported
   / SixLabors.ImageSharp.Formats.Tiff.TiffThrowHelper.ThrowNotSupported(String message)
   / SixLabors.ImageSharp.Formats.Tiff.TiffDecoderCore.Decode[TPixel](BufferedReadStream stream, CancellationToken cancellationToken)
   / SixLabors.ImageSharp.Formats.ImageDecoderUtilities.Decode[TPixel](IImageDecoderInternals decoder, Configuration configuration, Stream stream, Func`3 largeImageExceptionFactory, CancellationToken cancellationToken)
   / SixLabors.ImageSharp.Formats.ImageDecoderUtilities.Decode[TPixel](IImageDecoderInternals decoder, Configuration configuration, Stream stream, CancellationToken cancellationToken)
   / SixLabors.ImageSharp.Formats.Tiff.TiffDecoder.Decode[TPixel](Configuration configuration, Stream stream, CancellationToken cancellationToken)
   / SixLabors.ImageSharp.Formats.Tiff.TiffDecoder.Decode(Configuration configuration, Stream stream, CancellationToken cancellationToken)
   / SixLabors.ImageSharp.Image.<>c__DisplayClass117_0.<Load>b__0(Stream s)
   / SixLabors.ImageSharp.Image.WithSeekableStream[T](Configuration configuration, Stream stream, Func`2 action)
   / SixLabors.ImageSharp.Image.Load(Configuration configuration, Stream stream, IImageDecoder decoder)
   / SixLabors.ImageSharp.Image.Load(Configuration configuration, String path, IImageDecoder decoder)
   / SixLabors.ImageSharp.Image.Load(String path, IImageDecoder decoder)
   / Infrastructure.Images.Tiff.ImageSharpImageZip.IsUnzipPassable(String imagePath) 파일 D:\...\ImageSharpImageZip.cs:줄 19
   / Collector.Service.Services.Images.DefectImageUnZipManager._unzipSelection(String imageFilePath, String unzipDirectory, String unzipPrefixName) 파일 D:\...DefectImageUnZipManager.cs:줄 111
   / Collector.Service.Services.Images.DefectImageUnZipManager.ExcutorUnZip(MireroType mireroType, String imagesDirectory, String unzipDirectory) 파일 D:\...\DefectImageUnZipManager.cs:줄 54
```

### Steps to Reproduce

-

**Comment by JimBobSquarePants** [comment] 2022-07-14 13:11
Duplicate of #2113

As the exception describes. Tiff files with frames of different dimensions are not currently supported.

**Closed by JimBobSquarePants** 2022-07-14 13:11 UTC
Labels: needs triage
