### ISSUE TITLE
Picture Direction Error

### ISSUE THREAD

**Issue by wujunchengman** [SixLabors/ImageSharp#2809] opened 2024-09-10 03:36 UTC
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have verified that I am running the latest version of ImageSharp
- [X] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [X] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### ImageSharp version

3.1.5

### Other ImageSharp packages and versions

3.14

### Environment (Operating system, version and so on)

Linux both Windows

### .NET Framework version

6.0、8.0

### Description

```csharp
var imageInfo = Image.Identify(fileName);
```
the imageInfo，the width and height are reversed

### Steps to Reproduce

[IMG_0203.zip](https://github.com/user-attachments/files/16939014/IMG_0203.zip)

**Comment by JimBobSquarePants** [comment] 2024-09-10 03:38
Duplicate of invalid issue #2736

**Closed by JimBobSquarePants** 2024-09-10 03:38 UTC
Labels: needs triage
