### ISSUE TITLE
Images created via safari's/iOS's implementation of HTMLCanvasElement.toBlob cannot be loaded

### ISSUE THREAD

**Issue by jsfeldman** [SixLabors/ImageSharp#373] opened 2017-10-19 13:36 UTC
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of ImageSharp
- [ ] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

Images generated by canvas.toBlob in safari or iOS and then loaded into ImageSharp will fail with this error message:

```
System.NotSupportedException: Image cannot be loaded. Available decoders:
 - JPEG : JpegDecoder
 - PNG : PngDecoder
 - BMP : BmpDecoder
 - GIF : GifDecoder
```

### Steps to Reproduce

1. Draw an image on a canvas in Safari or iOS
2. Generate a blob from the canvas using toBlob
3. Create a url for the blob using URL.createObjectURL
4. Go to link and save file.

Here's an image file already created from this process that should have the same issue:

![](https://files.gitter.im/ImageSharp/General/NIPY/safari_failure_example.jpg)

Let me know if you need any other information.

### System Configuration

- ImageSharp version:
- Other ImageSharp packages and versions:
- Environment (Operating system, version and so on):
- .NET Framework version:
- Additional information:

**Comment by JimBobSquarePants** [comment] 2017-10-20 00:29
I've handled this before, we just need to add a few more header identifiers. Will update asap.

**Comment by antonfirsov** [comment] 2018-01-03 19:35
@jsfeldman what is your OS + .NET Framework version to run ImageSharp?

**Comment by jsfeldman** [comment] 2018-01-03 20:17
I believe I was using Safari 10 and 1.1 or 2.0-preview of .NET Core at the time.

Because I was using ImageSharp only for resizing images I wrote my code to catch any errors ImageSharp throws and just save the image without resizing it if ImageSharp errors out. However, for a while now I haven't seen any errors in the logs and I receive requests from a variety of devices. I was thinking you all had possibly fixed the issue (or maybe safari did, or I just wrote the code wrong).

I can close the issue if you want.

**Comment by antonfirsov** [comment] 2018-01-03 22:56
> I believe I was using Safari 10 [...]

@jsfeldman an I mean the OS you use to run `dotnet` to read the image, not the software you use to save it. I can't find this information in your report.

Someone reported a similar issue on our [gitter channel](https://gitter.im/ImageSharp/General), and I have a suspicion that the issue is specific to Unix-based systems.

Please don't close the issue :) We need to find out if it's ImageSharp-related.

**Comment by jsfeldman** [comment] 2018-01-03 23:25
Oh haha, I see. I was experiencing the issue on Windows 10. I think it might have occurred on Windows Server 2016 as well, but can't be sure.

**Comment by JimBobSquarePants** [comment] 2018-01-04 01:44
I wasn't able to replicate this with the given image btw.

**Comment by masteroleary** [comment] 2019-07-15 02:12
Any fix for this?

**Comment by JimBobSquarePants** [comment] 2019-07-15 02:13
Read the comment above

**Comment by JimBobSquarePants** [comment] 2019-07-15 02:34
@masteroleary Are you using streams at all to load the blob data? If so is your stream at the correct position when you call our API?

**Comment by masteroleary** [comment] 2019-07-15 21:54
The problem line is (which builds a stream directly from the byte data so the position should always be correct)
    
            Image<Rgba32> image = Image.Load(new System.IO.MemoryStream(bytes));

The issue happens sporadically and only recently started within the last 12 months although the app source code has not changed.

The issue can only be reproduced when uploading multiple .jpeg files from our app using various iPhones.

The strange part is that the same file can be uploaded successfully after a couple tries.

**Comment by JimBobSquarePants** [comment] 2019-07-16 03:57
> The strange part is that the same file can be uploaded successfully after a couple tries.

Then you are having communication issues and the delivered bytes are incomplete.

**Closed** 2019-10-24 23:47 UTC
Labels: area:bug, area:formats:jpeg
