### ISSUE TITLE
Jpg Image weight pretty higher than expected

### ISSUE THREAD

**Issue by ollie10** [SixLabors/ImageSharp#2005] opened 2022-02-16 10:58 UTC
### ImageSharp version

2.0.0

### Other ImageSharp packages and versions

None

### Environment (Operating system, version and so on)

Visual Studio 2022 + Windows 11

### .NET Framework version

.NET 6.0

### Description

Good Morning,

I noticed that latest version (2.0) of ImageSharp is creating images that are bigger in size than expected, I don't know if previous versions are also affected.

I'm doing a simple image resizing and EXIF removal with this code

```csharp
public static MemoryStream ResizeAndCropImage(string originalImage, ImageTypeEnum size)
		{
			using (Image image = Image.Load(originalImage))
			{
				ResizeOptions options = new ResizeOptions() { Size = new Size(MEDIUM_WIDTH, MEDIUM_HEIGHT), Position = AnchorPositionMode.Center, Mode = ResizeMode.Crop };

				if (size == ImageTypeEnum.Large)
					options = new ResizeOptions() { Size = new Size(LARGE_WIDTH, LARGE_HEIGHT), Position = AnchorPositionMode.Center, Mode = ResizeMode.Crop };

				JpegEncoder encoder = new JpegEncoder() { Quality = IMAGE_QUALITY, ColorType = JpegColorType.Rgb };

				MemoryStream resizedImage = new MemoryStream();

				image.Mutate(x => x.AutoOrient().Resize(options));

				//REMOVING EXIF TAGS
				if (image.Metadata != null && image.Metadata.ExifProfile != null && image.Metadata.ExifProfile.Values.Count > 0)
				{
					ExifTag[] tags = image.Metadata.ExifProfile.Values.Select(c => c.Tag).ToArray();
					foreach (ExifTag value in tags)
					{
						image.Metadata.ExifProfile.RemoveValue(value);
					}
				}

				image.Save(resizedImage, encoder);

				return resizedImage;
			}
		}
```

Now the biggest size I'm resizing is **1280x960** with a quality of **60** in **JPEG**.

I noticed two things mainly

1. The first one is that the image produced has always a resolution of **96 DPI** despite the original one has 72. Is there a way to set the resolution according with the original image? I tried to find the solution in the documentation but I found only outdated examples
2. The same settings used to reduce the image in Photoshop (always 1280x960 @60 quality) produces an image normally with ~100/150 Kb less than Imagesharp. I'm speaking about 400Kb against ~250Kb.

Tried with multiple images and it happens with almost all of them, it's clear I don`t expect results equal to Photoshop but a difference of 40% in size with same parameters it seems pretty high
Any Idea to reduce the size of the image

### Steps to Reproduce

Code added to the description

**Comment by JimBobSquarePants** [comment] 2022-02-16 11:11
This is likely a duplicate of #1996 

```c#
image.Metadata.ExifProfile = null;
image.Metadata.XmpProfile = null;
image.Metadata.IptcProfile = null;
```

There's no need to do a null check on `Metadata`

**Comment by ollie10** [comment] 2022-02-16 11:28
Hello, sorry to correct you, probably you didn't read the message, the problem is not regarding the EXIF tags (even if your code comes handy), the problem is about image size

**Comment by tocsoft** [comment] 2022-02-16 11:36
The exif/xmp data take up space in the final image and @JimBobSquarePants is suggesting you need to ensure you don't have any other metadata stashed in the image first.

So if you can verify you still have an issue if you follow the advice of trying to null out all 3 metadata profiles then we can potentially look further.

**Comment by JimBobSquarePants** [comment] 2022-02-16 11:46
>sorry to correct you, probably you didn't read the message

I absolutely did read the message so please do not suggest otherwise.

ImageSharp supports multiple metadata formats. You have cleared out one (_in an inefficient manner_). I have suggested that you should remove all of them and compare the result. 

Given that you haven't supplied a means of replicating your proposed issue (_An image representing your proposed issue and comparison output image_) there is very little (nothing) I can do other than suggest you check other metadata formats. 

Please Note: 

> Is there a way to set the resolution according with the original image

Please do not compound multiple questions within a single issue submission. ImageSharp is provided [AS IS](https://github.com/SixLabors/ImageSharp/blob/f24b02f31c2147a76a8d9894674d889ab194dbbf/LICENSE#L145) unless you have purchased a support license. 

>I tried to find the solution in the documentation but I found only outdated examples

Properties responsible for setting the resolution (completely unrelated to output file size) are clearly documented
- [HorizontalResolution](https://docs.sixlabors.com/api/ImageSharp/SixLabors.ImageSharp.Metadata.ImageMetadata.html#SixLabors_ImageSharp_Metadata_ImageMetadata_HorizontalResolution)
- [VerticalResolution](https://docs.sixlabors.com/api/ImageSharp/SixLabors.ImageSharp.Metadata.ImageMetadata.html#SixLabors_ImageSharp_Metadata_ImageMetadata_VerticalResolution)
- [ResolutionUnits](https://docs.sixlabors.com/api/ImageSharp/SixLabors.ImageSharp.Metadata.ImageMetadata.html#SixLabors_ImageSharp_Metadata_ImageMetadata_ResolutionUnits)

**Comment by br3aker** [comment] 2022-02-16 14:33
> I noticed that latest version (2.0) of ImageSharp is creating images that are bigger in size than expected

Expected compared to photoshop or version (1.x)? Please provide an example image, there's no way to determine the exact reason you're getting this behaviour without a concrete example.

**Comment by ollie10** [comment] 2022-02-16 15:27
Hello Again @JimBobSquarePants, sorry to misunderstand, I was thinking you mentioned that that the 150Kb of overhead it was due to the metadata, but I'm sure you didn't mean this because 40% of higher size it cannot be something due to the metadata.

So here you have a compete example with images and the result is even more concerning (@br3aker) :
Full code

```cs
private const int LARGE_WIDTH = 1280;
private const int LARGE_HEIGHT = 960;

private const int IMAGE_QUALITY = 60;
private const int IMAGE_RESOLUTION = 72;

public static MemoryStream ResizeAndCropImage(string originalImage, ImageTypeEnum size)
{
	using (Image image = Image.Load(originalImage))
	{
		ResizeOptions options = new ResizeOptions() { Size = new Size(MEDIUM_WIDTH, MEDIUM_HEIGHT), Position = AnchorPositionMode.Center, Mode = ResizeMode.Crop };

		if (size == ImageTypeEnum.Large)
			options = new ResizeOptions() { Size = new Size(LARGE_WIDTH, LARGE_HEIGHT), Position = AnchorPositionMode.Center, Mode = ResizeMode.Crop };

		JpegEncoder encoder = new JpegEncoder() { Quality = IMAGE_QUALITY, ColorType = JpegColorType.Rgb };

		MemoryStream resizedImage = new MemoryStream();

		image.Mutate(x => x.AutoOrient().Resize(options));

		//REMOVING EXIF TAGS AND SET THE RESOLUTION
		image.Metadata.ExifProfile = null;
		image.Metadata.XmpProfile = null;
		image.Metadata.IptcProfile = null;
		image.Metadata.HorizontalResolution = IMAGE_RESOLUTION;
		image.Metadata.VerticalResolution = IMAGE_RESOLUTION;

		image.Save(resizedImage, encoder);

		return resizedImage;
	}
}
```
Original Image: [Link](https://filetransfer.io/data-package/nObNMQhb#link) 3,18 Mb 72 DPI

So I ran 3 tests (same export size 1280x960)

1. Image exported with Gimp, 60% quality, nothing else flagged [See my settings](https://ibb.co/kMbQxGz) - Result a file of 195Kb at 72 DPI [See Gimp Result](https://filetransfer.io/data-package/1qZbB9js#link)
2. Image worked with **ImageSharp 2.0** with the code above - Result a file of 476Kb at 96 DPI [See V2 Result](https://filetransfer.io/data-package/jwiCmwUB#link)
3. Image worked with ImageSharp 1.0.4 with the code above (slight change) - Result a file of 172Kb at 72 DPI [See V1 Result](https://filetransfer.io/data-package/GUJBCyqj#link) 

We are speaking about a more than 100% difference against V1

The only changes I needed to do in V1 to be back compatible was removing **ColorType = JpegColorType.Rgb** (V1 doesn't have this property) and removing **image.Metadata.XmpProfile = null;** (V1 doesn't have XMP profile), nothing else changed.

Besides that V2 doesn't respect the 72 DPI setted neither takes them from the original image.

**Comment by brianpopow** [comment] 2022-02-16 16:02
@ollie10 you are you using `JpegColorType.Rgb`, this is the reason for the bigger size. Its more data to be compressed then YUV420, so that is an expected behavior. You should use `YCbCrRatio420`, the default, then the image size is the same as V1. With YUV420 the chroma data is halfed compared to RGB.

**Comment by ollie10** [comment] 2022-02-16 16:17
@brianpopow Oh, I see, just tried and now I have the same exact size of the V1, somehow I don't know why I was expected that the V1/V2 internally were using RGB.

Anyway the last thing, it seems useless to add the 72 DPI at this point since they are not taken into account, with YCbCrRatio420 it comes already an image with this resolution, it depends on the ColorType? Anyway thanks again

**Closed** 2022-02-16 17:11 UTC
