### ISSUE TITLE
[IOS Xamarin] System.ExecutionEngineException: Attempting to JIT compile method 'void SixLabors.ImageSharp.Formats.Png.PngScanlineProcessor:ProcessRgbScanline<SixLabors.ImageSharp.PixelFormats.Rgba32>

### ISSUE THREAD

**Issue by MichielDG** [SixLabors/ImageSharp#1708] opened 2021-07-19 12:40 UTC
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of ImageSharp
- [x] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
In a xamarin forms for IOS project I'm using the method Image.Load to load a PNG image. I used it with imagedecoder and without but the same issue exists. The error I get is:
```
PngDecoderCore.ProcessDefilteredScanline[TPixel] (System.ReadOnlySpan`1[T] defilteredScanline, SixLabors.ImageSharp.ImageFrame`1[TPixel] pixels, SixLabors.ImageSharp.Formats.Png.PngMetadata pngMetadata)
System.ExecutionEngineException: Attempting to JIT compile method 'void SixLabors.ImageSharp.Formats.Png.PngScanlineProcessor:ProcessRgbScanline<SixLabors.ImageSharp.PixelFormats.Rgba32> (SixLabors.ImageSharp.Configuration,SixLabors.ImageSharp.Formats.Png.PngHeader&,System.ReadOnlySpan`1<byte>,System.Span`1<SixLabors.ImageSharp.PixelFormats.Rgba32>,int,int,bool,SixLabors.ImageSharp.PixelFormats.Rgb48,SixLabors.ImageSharp.PixelFormats.Rgb24)' while running in aot-only mode. See https://docs.microsoft.com/xamarin/ios/internals/limitations for more information.

Stack traces
SixLabors.ImageSharp.Formats.Png
PngDecoderCore.ProcessDefilteredScanline[TPixel] (System.ReadOnlySpan`1[T] defilteredScanline, SixLabors.ImageSharp.ImageFrame`1[TPixel] pixels, SixLabors.ImageSharp.Formats.Png.PngMetadata pngMetadata)
SixLabors.ImageSharp.Formats.Png
PngDecoderCore.DecodePixelData[TPixel] (System.IO.Compression.DeflateStream compressedStream, SixLabors.ImageSharp.ImageFrame`1[TPixel] image, SixLabors.ImageSharp.Formats.Png.PngMetadata pngMetadata)
SixLabors.ImageSharp.Formats.Png
PngDecoderCore.ReadScanlines[TPixel] (SixLabors.ImageSharp.Formats.Png.PngChunk chunk, SixLabors.ImageSharp.ImageFrame`1[TPixel] image, SixLabors.ImageSharp.Formats.Png.PngMetadata pngMetadata)
SixLabors.ImageSharp.Formats.Png
PngDecoderCore.Decode[TPixel] (SixLabors.ImageSharp.IO.BufferedReadStream stream, System.Threading.CancellationToken cancellationToken)
SixLabors.ImageSharp.Formats
ImageDecoderUtilities.Decode[TPixel] (SixLabors.ImageSharp.Formats.IImageDecoderInternals decoder, SixLabors.ImageSharp.Configuration configuration, System.IO.Stream stream, System.Func`3[T1,T2,TResult] largeImageExceptionFactory)
SixLabors.ImageSharp.Formats
ImageDecoderUtilities.Decode[TPixel] (SixLabors.ImageSharp.Formats.IImageDecoderInternals decoder, SixLabors.ImageSharp.Configuration configuration, System.IO.Stream stream)
SixLabors.ImageSharp.Formats.Png
PngDecoder.Decode[TPixel] (SixLabors.ImageSharp.Configuration configuration, System.IO.Stream stream)
SixLabors.ImageSharp.Formats.Png
PngDecoder.Decode (SixLabors.ImageSharp.Configuration configuration, System.IO.Stream stream)
SixLabors.ImageSharp
Image.Decode (System.IO.Stream stream, SixLabors.ImageSharp.Configuration config)
SixLabors.ImageSharp
Image+<>c__DisplayClass137_0.<Load>b__0 (System.IO.Stream s)
SixLabors.ImageSharp
Image.WithSeekableStream[T] (SixLabors.ImageSharp.Configuration configuration, System.IO.Stream stream, System.Func`2[T,TResult] action)
SixLabors.ImageSharp
Image.Load (SixLabors.ImageSharp.Configuration configuration, System.IO.Stream stream, SixLabors.ImageSharp.Formats.IImageFormat& format)
SixLabors.ImageSharp
Image.Load (SixLabors.ImageSharp.Configuration configuration, System.Byte[] data, SixLabors.ImageSharp.Formats.IImageFormat& format)
SixLabors.ImageSharp
Image.Load (System.Byte[] data, SixLabors.ImageSharp.Formats.IImageFormat& format)
```

### Steps to Reproduce
Use an IOS Xamarin project and execute the following code:
```
byte[] imageData; // fill this with a png
var imageDecoder = new SixLabors.ImageSharp.Formats.Png.PngDecoder();
var image = Image.Load(imageData, imageDecoder);
```

- ImageSharp version: 1.0.3
- Environment (Operating system, version and so on): IOS 14.5
- .NET Standard: 2.0

**Comment by JimBobSquarePants** [comment] 2021-07-19 13:35
You've chopped off the first line of the exception message that tells us the exception thrown can you please supply it? 

Can you also update the target framework. It can't be .NET Standard 2.0 unless it is a class library.

**Comment by MichielDG** [comment] 2021-07-20 13:58
> You've chopped off the first line of the exception message that tells us the exception thrown can you please supply it?
> 
> Can you also update the target framework. It can't be .NET Standard 2.0 unless it is a class library.
> 
> We'll also need the image.
> 
> ### Edit.
> Just realized you put the exception in the title. You'll need to raise this upstream. It's an issue with the Xamarin AOT compiler not with ImageSharp. See this note as to why. [#1703 (comment)](https://github.com/SixLabors/ImageSharp/issues/1703#issuecomment-882319202)
> 
> We have tried to patch our way around issues so I would suggest trying one of our nightly builds to see if we've managed to avoid this particular issue.

It is implemented in a class library. That class library is used inside an Xamarin Forms IOS project (Xamarin Forms version 5.0.0.2012).
I just tried SixLabors.ImageSharp version 1.0.4-alpha.0.49. I have the same issue with this version.
I have the problem with every picture that is taken with the [Xamarin.Essentials.MediaPicker](https://docs.microsoft.com/en-us/xamarin/essentials/media-picker?tabs=ios) in IOS.

**Comment by JimBobSquarePants** [comment] 2021-07-20 15:21
Yeah it’s not the image (hence the reason I struck out the comment) it’s Xamarins AOT compiler. You should raise the issue upstream with them.

**Comment by softlion** [comment] 2021-08-11 17:10
Same issue.

It's because the template class is too complicated.

```
Error: Failed to save measurement (exception) | ExecutionEngineException: Attempting to JIT compile method 'void SixLabors.ImageSharp.Formats.Png.PngScanlineProcessor:ProcessRgbaScanline<SixLabors.ImageSharp.PixelFormats.Rgba32> (SixLabors.ImageSharp.Configuration,SixLabors.ImageSharp.Formats.Png.PngHeader&,System.ReadOnlySpan`1<byte>,System.Span`1<SixLabors.ImageSharp.PixelFormats.Rgba32>,int,int)' while running in aot-only mode. See https://docs.microsoft.com/xamarin/ios/internals/limitations for more information.
```

**Comment by JimBobSquarePants** [comment] 2021-08-11 21:57
> It's because the template class is too complicated.

I don’t understand what you mean by this

**Comment by JimBobSquarePants** [comment] 2021-08-11 21:58
Has anyone raised the the issue with Xamarin? As I said before. The issue is with their compiler

**Comment by softlion** [comment] 2021-08-11 22:14
They won't do anything. They are full on MAUI with a new AOT "compiler" (which may have the same limitations).

AOT can't, sometime, find out all the template classes that are used in a library. As live code generation is refused by apple devices.

**Comment by JimBobSquarePants** [comment] 2021-08-11 22:39
We don’t do any live code generation. No emit, nothing dynamic. Raise the issue with them.

**Comment by softlion** [comment] 2021-08-11 22:41
https://docs.microsoft.com/en-us/xamarin/ios/internals/limitations

see "Limited Generics Support"

**Comment by JimBobSquarePants** [comment] 2021-08-11 22:41
I’m closing this. The conversation has ceased to be constructive. There are no issues with the ImageSharp codebase

**Closed** 2021-08-11 22:40 UTC
Labels: area:aot, needs triage, upstream-issue
