### ISSUE TITLE
JPEG Encoding does not work on linux-arm

### ISSUE THREAD

**Issue by dontspeak** [SixLabors/ImageSharp#914] opened 2019-05-22 18:16 UTC
It seems that the JPEG ENcoder has issues when running on an linux-arm enviroment. this code:

`Image<Rgba32> testImage = Image.Load<Rgba32>("camera1280x960.jpg");`              
`using (var fs = new FileStream("localtest.jpg", FileMode.Create))`
`{`
`   testImage.SaveAsJpeg(fs);`
`   fs.Flush();`
`   fs.Close();`
`}`

works perfect on a Windows environment, but putting it onto an Raspbian (with .NET Core 2.2 installed) produces an corrupt JPEG file. As this problems does not occur when saving as PNG or BPM, it must be the JPEG ENcoder, and not the DEcoder.

source file:
![camera1280x960](https://user-images.githubusercontent.com/21156731/58198570-c8792300-7cce-11e9-9b91-f3757c7b0eeb.jpg)

saved file:
![localtest](https://user-images.githubusercontent.com/21156731/58198427-80f29700-7cce-11e9-8962-7a771c6291b1.jpg)

**Comment by antonfirsov** [comment] 2019-05-22 21:22
Duplicate of #871, please check the conversation there!

Unfortunately, no one in the team owns the hardware to reproduce the issue. If you (or @qdraw) can invest some time to do a deeper investigation for us, please let us know on our [gitter channel](https://gitter.im/ImageSharp/General)!

**Closed by antonfirsov** 2019-05-22 21:22 UTC
