### ISSUE TITLE
Load Image from an array of Bytes invert color

### ISSUE THREAD

**Issue by dfornero** [SixLabors/ImageSharp#2115] opened 2022-05-11 19:47 UTC
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have verified that I am running the latest version of ImageSharp
- [X] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [X] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### ImageSharp version

2.1.1

### Other ImageSharp packages and versions

2.1.1

### Environment (Operating system, version and so on)

Windows 10

### .NET Framework version

Net Core 3.1

### Description

Hello again; I can load an image (tiff format with differents sizes) from an array of bytes using "FrameDecodingMode.First"; so far so god. But randomly, the library load the image inverting colors (black & white, insted white & black). the original image is white with black lines; sometimes, it load the image as black with white lines. Any help? Thanks a lot...

### Steps to Reproduce

byte[] tiffImage = GetImageFromBytes(); // this load the array with one image from a database
TiffDecoder decoder = new TiffDecoder();
decoder.DecodingMode = FrameDecodingMode.First;
using (Image img = Image.load(tiffImage, decoder);
{
}

**Comment by JimBobSquarePants** [comment] 2022-05-11 22:04
You’re supposed to provide means to reproduce issues. You have not done that. 

If you are unable to do so we will have to close this issue.

**Comment by dfornero** [comment] 2022-05-12 00:28
Sorry, my mistake; I send you two images; they are only examples. I can not send you the real images, but i think they represent the situation.

![Imagen2](https://user-images.githubusercontent.com/101743355/167968334-2cae6c18-7f4b-4fc2-9daa-7208f316bd2c.jpg)
![Imagen1](https://user-images.githubusercontent.com/101743355/167968344-93001557-7752-42d7-bc4b-59d296df76ec.jpg)

**Comment by brianpopow** [comment] 2022-05-12 07:46
@dfornero the images you have provided are jpg images and not tiff images.

**Comment by dfornero** [comment] 2022-05-12 11:39
Hi; Unfortunely I can not send you the original images; they are confidential information. I send you two jpg just to ilustrate what happen in this case.

**Comment by JimBobSquarePants** [comment] 2022-05-12 11:43
Then I’m afraid the only way this potential issue could be fixed is by someone from your side submitting a PR with the fix. Without a means to replicate we have nothing to debug.

**Comment by dfornero** [comment] 2022-05-12 11:45
Ok, thanks any way.

**Comment by br3aker** [comment] 2022-05-24 13:11
@brianpopow wait, TIFF images can be encoded with jpeg YccK color, right?

Usually such 'inverted' images could be generated via invalid rgb -> ycck conversion formula:

```cs
// rgb -> cmyk
CmykScalar.ConvertFromRgb(in values, maxValue, rLane, gLane, bLane);

// cmyk -> ycck
Span<float> c = values.Component0;
Span<float> m = values.Component1;
Span<float> y = values.Component2;

for (int i = 0; i < y.Length; i++)
{
    // color inversion here
    float r = maxValue - c[i];
    float g = maxValue - m[i];
    float b = maxValue - y[i];

    // k value is passed untouched from rgb -> cmyk conversion
    c[i] = (0.299f * r) + (0.587f * g) + (0.114f * b);
    m[i] = halfValue - (0.168736f * r) - (0.331264f * g) + (0.5f * b);
    y[i] = halfValue + (0.5f * r) - (0.418688f * g) - (0.081312f * b);
}
```

We also don't write APP14 marker for CMYK images which can be misinterpreted by some image showing software. CMYK/YccK is the only part in the jpeg format which can cause this (is given images actually used jpeg compression).

**Comment by brianpopow** [comment] 2022-06-10 17:14
@CREFaulk without the image, it's nearly impossible to tell what's wrong (I guess something goes wrong while decoding). 

What happens, when you convert the image to a png with imagemagick? 

`magick convert image.tiff image.png`

Does the resulting png look as you expect? Is it different from what ImageSharp produces when you save it as a PNG?

**Comment by CREFaulk** [comment] 2022-06-10 17:22
Here is the image info from imagemagick. https://pastebin.com/eaB7puQ6

If I convert to a png it looks as it should although obviously as separate images.

**Comment by brianpopow** [comment] 2022-06-10 17:41
Thanks for the image info. Nothing too fancy there. Endianess is lsb, tiff:photometric: min-is-black and compression is group4. We have such test images in our unit tests working.

> If I convert to a png it looks as it should although obviously as separate images. I'll see if I can create a test image in our repository that can reproduce the issue.

How did you convert it? Does converting with imagemagick work as expected or converting with ImageSharp to PNG also works as expected, but not when you encode it as Tiff?

**Comment by CREFaulk** [comment] 2022-06-10 18:05
`public byte[] PdfFromImage( string fileName, byte[] documentBytes )
{
	byte[] byteResult;

	using ( var ms = new MemoryStream( documentBytes ) )
	{
		var document = new Aspose.Pdf.Document();
		ms.Position = 0;
		IImageFormat format;
		var imageHeight = 0;
		var imageWidth = 0;
		var bytes = ms.ToArray();
		using ( SixLabors.ImageSharp.Image bitmap = SixLabors.ImageSharp.Image.Load( ms, out format ) )
		{
			for ( var i = 0; i < bitmap.Frames.Count; i++ )
			{
				var frame = bitmap.Frames.CloneFrame( i );
				// If bitmapStream is disposed then pdf will not save with "Cannot access a closed Stream."
				// If declared separately then every page is the first page
				var bitmapStream = new MemoryStream();
				frame.SaveAsPng( bitmapStream );
				imageHeight = frame.Height;
				imageWidth = frame.Width;

				var newPage = document.Pages.Add();
				Aspose.Pdf.Image img = new Aspose.Pdf.Image();
				img.ImageStream = bitmapStream;
				img.HorizontalAlignment = HorizontalAlignment.Center;
				img.VerticalAlignment = VerticalAlignment.Center;
				newPage.Paragraphs.Add( img );
				newPage.Background = Aspose.Pdf.Color.White;
				newPage.PageInfo.IsLandscape = imageWidth > imageHeight;
				newPage.PageInfo.Height = newPage.PageInfo.IsLandscape ? imageWidth : imageHeight;
				newPage.PageInfo.Width = newPage.PageInfo.IsLandscape ? imageHeight : imageWidth;

				if ( newPage.PageInfo.Height < PORTRAIT_PAGE_HEIGHT )
				{
					newPage.PageInfo.Height = PORTRAIT_PAGE_HEIGHT;
				}
				if ( newPage.PageInfo.Width < PORTRAIT_PAGE_WIDTH )
				{
					newPage.PageInfo.Width = PORTRAIT_PAGE_WIDTH;
				}
				newPage.PageInfo.Margin.Bottom = 1;
				newPage.PageInfo.Margin.Top = 1;
				newPage.PageInfo.Margin.Left = 1;
				newPage.PageInfo.Margin.Right = 1;
			}
			using ( var pdfStream = new MemoryStream() )
			{
				document.Save( pdfStream, SaveFormat.Pdf );
				byteResult = pdfStream.ToArray();
			}              
		}
		ms.Close();
	}
	return byteResult;
}`

**Comment by brianpopow** [comment] 2022-06-10 20:20
> In c#, I tried converting the tiff pages to tiff, png, and jpg with the same inverted black/white results. I'm loading the pages into a pdf. The pages are right but just with the black/white reversed.

That means the decoder could be the problem. Again without a test image, I cannot do much.

> My wip code is in the next message. Apologies to OP for hijacking the thread but hopefully this is the same issue since the results are identical.

Most of the code has nothing to do with ImageSharp, try simplify the example.

**Comment by CREFaulk** [comment] 2022-06-10 22:14
Well, I guess I could have tried the obvious...
if(format.Name.Equals("TIFF"))
{
    frame.Mutate( x => x.Invert() );
}

I'm getting images from a third party repository and in my case they have social security numbers and whatnot in them so creating a test image that matches the original might be tricky. Pretty sure the issue is with the original PhotoMetric setting.

I'll see if I can reproduce with an image I create manually and write a unit test to reproduce it but the above will work for now as long as they are all reversed. :|

Standard system.drawing.common code didn't have the reversed appearance issue but only worked in Windows and not at all in the current non-windows environment I deploy to even with the System.Drawing.EnableUnixSupport template option.

**Comment by brianpopow** [comment] 2022-08-24 18:28
Closing this now, because without a test image this can not be reproduced. @CREFaulk feel free to open/comment here again, if you manage to get a image with that issue (which can be shared).

**Closed by brianpopow** 2022-08-24 18:28 UTC
Labels: formats:tiff, needs triage
