### ISSUE TITLE
DrawText is broken in last version (1.0.0-beta0003)

### ISSUE THREAD

**Issue by lukapor** [SixLabors/ImageSharp#509] opened 2018-03-28 08:27 UTC
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of ImageSharp
- [ ] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
I using DrawText for avatar image. With new version i can not get initials on avatar image

### Steps to Reproduce
I downloaded latest source code. And ran DrawAB() test. Produced image was not expected see attachment file
![ab](https://user-images.githubusercontent.com/3388840/38016374-147db9d8-326f-11e8-9119-fc2052509f4c.png)

### System Configuration
Windows system

- ImageSharp version: 1.0.0-beta0003
- Other ImageSharp packages and versions: -
- Environment (Operating system, version and so on): Windows
- .NET Framework version: dotnet 2.0
- Additional information:

**Comment by tocsoft** [comment] 2018-03-28 08:30
Please explain why that image is wrong. Just because something is unexpected for you doesn't mean its wrong.

**Comment by lukapor** [comment] 2018-03-28 08:46
Sorry, this image is probably expected, but when I tried processing with dotnet 2.1 (netcoreapp2.1), i got only blue image (without text)

![ab](https://user-images.githubusercontent.com/3388840/38018484-4afc395c-3275-11e8-817a-a0152d344a4c.png)

**Comment by tocsoft** [comment] 2018-03-28 08:50
this looks like its probably related to #504

**Comment by lukapor** [comment] 2018-03-28 11:42
Some additional data:
- on Windows platform i got empty image (without text)
- on Linux platform (ubuntu) i got expected image (with text)

**Comment by JimBobSquarePants** [comment] 2018-03-28 14:01
Definitely seems like #504 then. We might have to take a performance hit there to fix it as it’s caused by bad inlining.

**Comment by JimBobSquarePants** [comment] 2018-03-28 14:06
@lukapor Can you please confirm for me that the issue exists in release mode only?

**Comment by lukapor** [comment] 2018-03-28 15:33
Hi my problem exist on both mode (debug, release) on windows. I also display vector parameter mention on #504. In release mode is corrupted in debug is ok.

On linux vector parameters are correct in both mode and also got expected image on both mode.

So problem on windows stay it is not depend on build mode.

**Comment by antonfirsov** [comment] 2018-05-26 21:52
@tocsoft isn't this how the `SixLaborsSampleAB.woff` font intentionally looks like?

The output looks fine with `OpenSans-Regular.ttf`:
- [Tests](https://github.com/SixLabors/ImageSharp/blob/196d40515a2457af66ef59fab174a910a85e36bd/tests/ImageSharp.Tests/Drawing/Text/DrawTextOnImageTests.cs#L38)
- [Results](https://github.com/SixLabors/Imagesharp.Tests.Images/tree/master/ReferenceOutput/Drawing/Text/DrawTextOnImageTests)

**Comment by antonfirsov** [comment] 2018-05-28 12:27
@lukapor it would be very helpful if you could share the type of your CPU!
(Seems like these issues are HW specific)

**Comment by JimBobSquarePants** [comment] 2018-06-29 04:36
@lukapor Did you see @antonfirsov question? It would really help us out if you could provide that info.

**Comment by lukapor** [comment] 2018-06-29 05:19
Hi, I an on vacation. Soon i come back i will test if  issue exist on latest beta version and give you some nfo about hw

**Comment by JimBobSquarePants** [comment] 2018-06-29 06:12
Fantastic, thanks, we really appreciate that!

**Comment by JimBobSquarePants** [comment] 2018-08-31 18:05
Closing this as #504 is now fixed.

**Closed by JimBobSquarePants** 2018-08-31 18:05 UTC
Labels: area:drawing, bug
