### ISSUE TITLE
Bug in .NET 6.0 which does not occur in .NET 5.0 when saving and loading png

### ISSUE THREAD

**Issue by synercoder** [SixLabors/ImageSharp#1765] opened 2021-09-22 12:55 UTC
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have verified that I am running the latest version of ImageSharp
- [X] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [X] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
I use a library to render PDF pages to image data. This data is in BGRA format. I then use `Image.LoadPixelData<Bgra32>(bytes, width, height)` to load the data, and then use the data. 

In my unit test for this library I load the Bgra32 data after rendering, then save as PNG. Later on I open that file/stream again using `Image.Load`. It then throws an exception: `SixLabors.ImageSharp.ImageFormatException : Bad method for ZLIB header: cmf=32`.

### Steps to Reproduce
I have saved the raw bgra data into a file, and made a minimal bug sample. The test run on GitHub actions can be found here: https://github.com/synercoder/ImageSharpNet6Bug/runs/3675201091?check_suite_focus=true

As can the minimal sample test: https://github.com/synercoder/ImageSharpNet6Bug/blob/main/ImageSharpBugTests/BugTests.cs

### System Configuration

- ImageSharp version: 1.0.3
- Environment (Operating system, version and so on): Windows 10, bug also reproduced in GitHub Actions on Windows-latest
- .NET Framework version:  My pc & Github actions: 6.0.100-rc.1.21458.32
- Additional information: Works in .NET 5.0 & images used in the raw file are from [Pexels.com under the royalty-free license](https://www.pexels.com/license/) if that was any worry.

**Comment by antonfirsov** [comment] 2021-09-22 12:59
This is most likely duplicate of #1704, which got fixed by #1707.

Can you please check if it works with [the nighlties](https://www.myget.org/feed/sixlabors/package/nuget/SixLabors.ImageSharp)?

**Comment by synercoder** [comment] 2021-09-22 13:00
Will do...

**Comment by synercoder** [comment] 2021-09-22 13:05
My searching of the issues was not enough apparently, also works currently on my pc & github actions. So I guess close me as duplicate.

**Comment by synercoder** [comment] 2021-09-22 14:52
@antonfirsov could my test case / image be a good addition to the imagesharp test suit (as a regression test mayhaps)? If so I could create/shape a PR this evening/tomorrow.

**Comment by antonfirsov** [comment] 2021-09-22 15:15
Yeah #1707 went in without a test, a test case would be an addition we appreciate!

**Closed** 2021-09-22 16:30 UTC
Labels: needs triage
