### ISSUE TITLE
Resize from large source to small thumbnail produces deformed top pixel rows

### ISSUE THREAD

**Issue by patrikwlund** [SixLabors/ImageSharp#1006] opened 2019-09-09 17:28 UTC
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of ImageSharp
- [ ] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
Downsizing a large image can cause oddly sampled pixels in the top rows of pixels (I only noticed it in the top rows at least).

I tested multiple samplers. All of them displayed similar results.

### Steps to Reproduce
```
using (var image = Image.Load(flowersJpg))
{
    image.Mutate(i => i.Resize(new ResizeOptions
    {
        Size = new Size(300, 300),
        Mode = ResizeMode.Crop
    }));

    image.SaveAsJpeg(outputStream);
}
```

### System Configuration
- ImageSharp version: **1.0.0-beta0007**
- Other ImageSharp packages and versions:
- Environment (Operating system, version and so on): **Windows 10 (1903)**
- .NET Framework version: **4.7.1**
- Additional information:

### Source Image
![flowers](https://user-images.githubusercontent.com/6620662/64552149-ef6b6b80-d336-11e9-818b-2ef46a7cffe4.jpg)

### Example results

Resized with ImageSharp
![flowers_imagesharp](https://user-images.githubusercontent.com/6620662/64552161-f5614c80-d336-11e9-9d41-c390d7eff02a.jpg)

Resized with ImageResizer
![flowers_imageresizer](https://user-images.githubusercontent.com/6620662/64552164-f7c3a680-d336-11e9-81b9-79360ed5098f.jpg)

**Comment by scleaver** [comment] 2019-11-19 03:47
I am seeing the same issue in my site which is using ImageSharp but not always when dropping to a small image.

https://www.kast.io/media/concepts/group-ideas.jpg?width=1920&height=832&rmode=crop
https://demo.kast.io/media/groups-demo/family-groups2.jpg?width=408&height=316&rmode=crop

**Comment by JimBobSquarePants** [comment] 2019-11-19 03:49
@scleaver  Can you include the source images directly in this issue please, Just in case they get removed or updated on your servers. Thanks!

**Comment by scleaver** [comment] 2019-11-19 04:08
I think the issue is caused by the size of the source image.

![group-ideas](https://user-images.githubusercontent.com/2867511/69115838-da991a00-0ad5-11ea-9a00-5d29768eee8a.jpg)
![family-groups2](https://user-images.githubusercontent.com/2867511/69115843-dd940a80-0ad5-11ea-90a3-19b89f6609d1.jpg)

**Comment by JimBobSquarePants** [comment] 2019-11-19 04:57
Thanks @scleaver 

@antonfirsov one for you I think. Let me know if you need a second pair of eyes.

**Comment by netwavebe** [comment] 2019-11-19 08:28
I'm having the same issue. This is the top (zoomed in) of a very large image scaled to 480 x 600:
![CGPW460_2018](https://user-images.githubusercontent.com/3008547/69129587-f806bd80-0aae-11ea-83c4-05a4d6274f96.jpg)

**Comment by JimBobSquarePants** [comment] 2019-11-20 10:39
@netwavebe Please do. Thanks!

**Comment by netwavebe** [comment] 2019-11-20 11:47
Original image is 1980 x 5520:

![CGPW460_2018](https://user-images.githubusercontent.com/3008547/69236242-68870a80-0b93-11ea-91a7-1b392eda304e.jpg)

This image cropped to 480 x 600:

![CGPW460_2018_cropped_480x600](https://user-images.githubusercontent.com/3008547/69236263-70df4580-0b93-11ea-9cb1-d97414b2e9f5.jpg)

The top distortion is probably very visible here because we're cropping a lot in this image...

**Comment by JimBobSquarePants** [comment] 2019-11-20 11:51
@netwavebe I'm assuming you're simply passing the new width and height with `ResizeMode.Crop` yeah?

**Comment by netwavebe** [comment] 2019-11-20 12:34
@JimBobSquarePants Yes, exactly!

**Comment by JimBobSquarePants** [comment] 2019-12-05 03:04
@netwavebe Here's the output following my fix. @patrikwlund @scleaver Your images will resize correctly once merged. Thanks for your patience. 👍 

![CanResizeLargeImageWithCropMode_Rgba32_issue1006-incorrect-resize](https://user-images.githubusercontent.com/385879/70200250-e6d4d680-1767-11ea-8073-3c747e510055.png)

**Comment by netwavebe** [comment] 2019-12-05 07:26
@JimBobSquarePants : Awesome! 👍 
@scleaver : Once there is a new version, we need to update Orchard Core dev!

**Closed** 2019-12-08 04:45 UTC
Labels: area:bug, area:transforms
