### ISSUE TITLE
Resizing from PNG to JPG is done poorly in 2.0.0 and higher. It worked alright in 1.0.4

### ISSUE THREAD

**Issue by tinyTarrasque** [SixLabors/ImageSharp#2202] opened 2022-08-12 16:29 UTC
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have verified that I am running the latest version of ImageSharp
- [X] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [X] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### ImageSharp version

2.1.3

### Other ImageSharp packages and versions

1.0.4

### Environment (Operating system, version and so on)

Windows 11

### .NET Framework version

6.0

### Description

The app I am working on needs to convert PNGs to JPGs as well as resize them.

Using the following code with the version 1.0.4 works (Images averaging 150 to 200Kb), the same code in 2.0.0 all the way to 2.1.3 (Images averaging 4.5 to 4.8Mb)

### Steps to Reproduce

byte[] inputFile <- Here goes the loaded image. My current code retrieves the images from an Azure Blob repo.

Image image = Image.Load<Rgba32>(inputFile);
image.Mutate(x => x.BackgroundColor(Color.White)); // I've tried with this line and without it, it causes no difference
image.Mutate(x => x.Resize(width, height));

int quality = 85;
while (quality > 0)
{
    using MemoryStream ms = new();
    await image.SaveAsJpegAsync(ms, new JpegEncoder { Quality = quality });
    if ((ms.Length / 1024) <= 150)
    {
        return (ms.ToArray(), null);
    }
    else
        quality -= 5;
}

### Images

![Uploading 7506475103718_L5.png…]()

**Comment by tinyTarrasque** [comment] 2022-08-12 16:31
Unsure if the image uploaded properly. Here's the URL where you can get it:

https://theecontentstorage.blob.core.windows.net/tecs-imagenes/7506475103718_L5.png

**Comment by brianpopow** [comment] 2022-08-12 18:00
@tinyTarrasque It seems that the metadata is causing this. The XMP Profile is 4MB large. If you set it to null:
```
image.Metadata.XmpProfile = null;
```

the image size will be ok again.

**Comment by brianpopow** [comment] 2022-08-12 18:06
Now that I am thinking about it, there is maybe an issue here. The XMP profile should actually not exceed 65533 bytes.

**Comment by brianpopow** [comment] 2022-08-12 18:40
@tinyTarrasque Is it ok, if I use your image in a unit test?

**Comment by tinyTarrasque** [comment] 2022-08-12 18:44
@brianpopow Of course!

**Comment by br3aker** [comment] 2022-08-14 12:25
@tinyTarrasque can you please specify what's the exact problem you've encountered?
I've reencoded your image with current `main` branch build and got valid output jpeg image.

**Comment by tinyTarrasque** [comment] 2022-08-14 19:20
@br3aker How is converting an image to a 150kb file JPEG and then one version after (with exactly the same code) converting the same source image to a 4.5Mb file JPG "working as intended"?

And yes, the workaround does the job.

**Comment by brianpopow** [comment] 2022-08-14 19:33
@br3aker thanks for double checking this, I also think everything works as intended. My initial thought that the XMP data should be capped at 65k bytes was wrong. 

@tinyTarrasque are you not reading what we are commenting here? We said multiple times now, that the reason for the filesize being so big is mainly because of the 4 MB XMP data (XMP support was introduced with 2.0.0). What should we do with this data? How should we know, that you are not interested in saving it?

Closing this issue now.

**Closed by brianpopow** 2022-08-14 19:33 UTC
Labels: formats:jpeg
