### ISSUE TITLE
Corrupted text while scaling with TextMeasurer

### ISSUE THREAD

**Issue by MaddoScientisto** [SixLabors/ImageSharp#267] opened 2017-07-03 15:09 UTC
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of ImageSharp
- [x] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/JimBobSquarePants/ImageSharp/issuess) and [closed](https://github.com/JimBobSquarePants/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
While doing experiments in trying to write text on the image I ran into this weird text corruption issue:

![applicationframehost_2017-07-03_16-58-42](https://user-images.githubusercontent.com/816014/27798271-eead1964-6010-11e7-9773-e7344ee1bfda.png)

### Steps to Reproduce
An image is loaded `using (Image<Rgba32> image = Image.Load("image path"))` then text is applied with the following function and then saved with `image.save`
```
private void WriteTextFixed(Image<Rgba32> image)
        {
            var fo = SixLabors.Fonts.SystemFonts.Find("Microsoft Sans Serif");
            var font = new Font(fo, 8, FontStyle.Regular);
            Rgba32 g = Rgba32.FromHex("#FF00FFFF");
            Vector2 center = new Vector2(image.Width / 2, image.Height / 2);
            var size = TextMeasurer.Measure("Test test test test test", new RendererOptions(font));
            float scalingFactor = Math.Min(image.Width / size.Width, image.Height / size.Height);
            Font scaledFont = new Font(font, scalingFactor * font.Size);
            image.DrawText("Test test test test test", scaledFont, g, center, new TextGraphicsOptions(true) { HorizontalAlignment = HorizontalAlignment.Center, VerticalAlignment = VerticalAlignment.Bottom });
        }
```
It happens with different images too
### System Configuration

- ImageSharp version: 1.0.0-alpha9-00169
- ImageSharp.Drawing version: 1.0.0-alpha9-00164
- Environment (Operating system, version and so on): windows 10 x64
- .NET Framework version: 4.6
- Additional information: Vector.IsHardwareAccelerated is true

Original image: 
![madd4384](https://user-images.githubusercontent.com/816014/27798523-dbd2308a-6011-11e7-92d7-a305cd36c16e.JPG)

**Comment by JimBobSquarePants** [comment] 2017-09-26 12:30
@tocsoft I've assigned this to you since you're by far and away the expert here.

**Comment by MaddoScientisto** [comment] 2017-09-26 12:44
Updated reproducible code for latest beta:
```
private void SetTextTest(Image<Rgba32> image)
        {
            string text = "test test test test test testtest test test test test test test";
            Font font = new Font(SystemFonts.Find("verdana"), 300, FontStyle.Regular);
            image.Mutate(x => x.DrawText(text, font, Rgba32.Yellow, new PointF(2760, 3295.54932f), new TextGraphicsOptions()
            {
                HorizontalAlignment = HorizontalAlignment.Center
            }));
        }
```

Reference image: 
![ann_0975](https://user-images.githubusercontent.com/816014/30860885-209f9e92-a2c9-11e7-948d-66a3144401f6.JPG)

**Comment by woutware** [comment] 2018-05-22 13:22
This is a duplicate of https://github.com/SixLabors/ImageSharp/issues/572. I have verified it works ok after the fix (see attached images).

Test program:

```

        static void Main(string[] args) {
            Image<Rgba32> image = Image.Load<Rgba32>(@"D:\support\ImageSharp\Image.JPG");
            SetTextTest(image);
            using (Stream stream = File.Create(@"D:\support\ImageSharp\Image.out.JPG")) {
                image.SaveAsJpeg(stream);
            }
            Console.WriteLine("Hello World!");
            Console.ReadLine();
        }

        private static void SetTextTest(Image<Rgba32> image) {
            string text = "test test test test test testtest test test test test test test";
            Font font = new Font(SystemFonts.Find("verdana"), 300, FontStyle.Regular);
            image.Mutate(x => x.DrawText(new TextGraphicsOptions() {
                HorizontalAlignment = HorizontalAlignment.Center
            }, text, font, Rgba32.Yellow, new PointF(2760, 3295.54932f)));
        }
```

![image out-before-issue-572-fix](https://user-images.githubusercontent.com/35376607/40364906-adbc1330-5dd3-11e8-9ddf-1bec91166834.JPG)
![image out-after-issue-572-fix](https://user-images.githubusercontent.com/35376607/40364910-b057be0a-5dd3-11e8-941e-0a441fb70d26.JPG)

**Comment by JimBobSquarePants** [comment] 2018-05-23 10:38
Closing now as in nightlies

**Closed by JimBobSquarePants** 2018-05-23 10:38 UTC
Labels: area:drawing, bug
