### ISSUE TITLE
Some unit tests fail with SSE disabled (i.e. scalar path only)

### ISSUE THREAD

**Issue by gfoidl** [SixLabors/ImageSharp#2414] opened 2023-03-25 09:40 UTC
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have verified that I am running the latest version of ImageSharp
- [X] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [X] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### ImageSharp version

local build with latest main-branch

### Other ImageSharp packages and versions

none

### Environment (Operating system, version and so on)

win-x64, DOTNET_EnableSSE=0

### .NET Framework version

all

### Description

While hunting the bug (fixed via https://github.com/SixLabors/ImageSharp/pull/2413) I tried several things, amongst others disabling SSE for unit tests run with Visual Studio by using this https://github.com/SixLabors/ImageSharp/blob/0a1f05b746a6cf2e56b863bdc39705db20dff76a/.runsettings#L2
```xml
<?xml version="1.0" encoding="utf-8" ?>
<RunSettings>
    <RunConfiguration>
        <!--Used in conjunction with ActiveIssueAttribute to skip tests with known issues-->
        <TestCaseFilter>category!=failing</TestCaseFilter>

        <EnvironmentVariables>
            <DOTNET_EnableSSE>0</DOTNET_EnableSSE>
        </EnvironmentVariables>
    </RunConfiguration>
</RunSettings>
```
Tests started to fail -- even when going back in the history of main-branch (so no recent commit caused these failures).

To me it looks like there are latent bugs in the scalar code-pathes. Can anyone confirm?

<sub>(description copied and adapted from https://github.com/SixLabors/ImageSharp/pull/2413#issuecomment-1483340464)</sub>

### Steps to Reproduce

To reproduce together with that runsettings one can try this [playlist.zip](https://github.com/SixLabors/ImageSharp/files/11066186/playlist.zip) (for filtered tests).

**Comment by gfoidl** [comment] 2023-03-25 09:47
It looks like CI runs the tests on the agents "as is", so with AVX (except MacOS?) and SSE enabled. When the PR is labeled for ARM then an extra runner for ARM is started.

Thus bugs in the scalar code-paths may not be covered by CI, as the path via AVX/SSE is taken usually.
Some bugs get revealed by running on ARM (e.g. https://github.com/SixLabors/ImageSharp/pull/2409#issuecomment-1482798035) but CI should cover the scalar paths on non-ARM too.

My suggestion is to add a new entry in the https://github.com/SixLabors/ImageSharp/blob/302a23fc551fbd223b60a0ea066370e4a148594d/.github/workflows/build-and-test.yml#L16-L19 that
* e.g. `ubuntu-latest`
* has environment variable `DOTNET_EnableSSE=0` set
so that JIT treats `Sse.IsSupported = false` (and all "inherited" intrinsics like SSE2, ..., AVX, AVX2), thus only the scalar code-paths are executed.

**Comment by gfoidl** [comment] 2023-03-25 09:49
@brianpopow in https://github.com/SixLabors/ImageSharp/pull/2413#issuecomment-1483402414 you wrote about coverage.

Please check if there's coverage for https://github.com/SixLabors/ImageSharp/blob/ca21b6d53d4443413664d1dc6de9192e5199eec9/src/ImageSharp/Formats/Webp/Lossless/LosslessUtils.cs#L1459
I guess that's not covered, as it's a scalar-path and method `ClampedAddSubtractHalf` (which calls this method) has a pure SSE2-implemation too.

**Comment by JimBobSquarePants** [comment] 2023-03-25 11:41
We should be running any decoder/encoder tests using `FeatureTestRunner` with which we can disable Avx/Sse etc.

**Comment by brianpopow** [comment] 2023-03-25 18:09
> @brianpopow in [#2413 (comment)](https://github.com/SixLabors/ImageSharp/pull/2413#issuecomment-1483402414) you wrote about coverage.
> 
> Please check if there's coverage for
> 
> https://github.com/SixLabors/ImageSharp/blob/ca21b6d53d4443413664d1dc6de9192e5199eec9/src/ImageSharp/Formats/Webp/Lossless/LosslessUtils.cs#L1459
> 
> 
> I guess that's not covered, as it's a scalar-path and method `ClampedAddSubtractHalf` (which calls this method) has a pure SSE2-implemation.

Here is the [coverage report](https://app.codecov.io/github/SixLabors/ImageSharp/commit/d7cd46f503e0ffc9fc0149ab1f6f53de775ec8df/blob/src/ImageSharp/Formats/Webp/Lossless/LosslessUtils.cs) For LosslessUtils. `ClampedAddSubtractHalf` is reported as covered, but the `Clip255` which is called by `ClampedAddSubtractHalf` is only reported as covered partially. I think that's the problem.
I will improve the test, so it will be fully covered.

> We should be running any decoder/encoder tests using FeatureTestRunner with which we can disable Avx/Sse etc.

There is a test `RunPredictor13Test` which uses the `FeatureTestRunner` to run with and without intrinsics. For context: `Predictor13()` calls `ClampedAddSubtractHalf()`.

There are some paths not covered, for example `BundleColorMap()` and `SubtractGreenFromBlueAndRedScalar()`

**Comment by gfoidl** [comment] 2023-03-25 18:51
That's a bit strange. When the private method `AddSubtractComponentHalf` is covered, and that method had the bug, then it should have shown up. Or is the test -- ran via `FeatureTestRunner` -- only executing some inputs? 
I'm new to the test infrastructure here, so I have to ask?

Besides that I wonder why so many tests (10+) fail when SSE is disabled.

**Comment by brianpopow** [comment] 2023-03-26 11:31
The issue is in `Clip255`, this method is called by `AddSubtractComponentHalf`
and is not fully covered. Only the path `a < 256 == true` is covered, not the case `a < 256 == false`
This hides the error. This means we need two test cases for `RunPredictor13Test` one for `a < 256 == true` and one for `a < 256 == false`.
The when you revert back your commit b6949566 to have the issue, it will show up as a failed test.

`FeatureTestRunner` allows us to run tests with disabled intrinsics features.
For example:

```
FeatureTestRunner.RunWithHwIntrinsicsFeature(
            RunTest,
            count,
            HwIntrinsics.AllowAll | HwIntrinsics.DisableAVX2);
```

This will run `RunTest` with hardware intrinsics once and once without AVX2 (assuming the host cpu has AVX2).

> Besides that I wonder why so many tests (10+) fail when SSE is disabled.

I had no chance yet to look into those failing tests, but we need to fix them all.

**Comment by gfoidl** [comment] 2023-03-26 12:46
`FeatureTestRunner` is a nice solution. Thanks for the explanaition 👍🏻 

Is the cost of running of a whole CI-leg with SSE disabled too high?
Or can this be run only on a scheduled basis?
So all code-paths w/o vectorization are touched, and no one has to think about adding a test-case with the FeatureTestRunner.

**Comment by JimBobSquarePants** [comment] 2023-03-26 13:54
To cover all the intrinsic paths on 4 OS (linux is counted 2x now we have ARM) for 2X target frameworks the build matrix explodes to something like 28 images now.

`FeatureTestRunner` was my workaround to keep numbers low and also so we could get a detailed code coverage report from a single entry in the build matrix.

I don't think there's a way to keep our coverage report intact while splitting out the features into separate matrix entries.

I would suggest we ensure that all decoder/encoder methods use `FeatureTestRunner` for Avx, Sse, AdvancedSimd, and scalar runs. It's a chore but absolutely necessary.

**Comment by gfoidl** [comment] 2023-03-26 14:14
> the build matrix explodes

This should be avoided, for sure.
I'd do only +1, so run a additional `ubuntu-latest` with `DOTNET_EnableSSE=0` set. So that scalar pathes are touched at least once (for sure).
If there's a test missing for running via `FeatureTestRunner` code will be covered too.

I'm not that familiar with GH-Actions (I'm using Azure Pipelines mostly) but I think that should be possible w/o exploding the matrix.

`FeatureTestRunner` is good and should be kept, as tests can be run on other operating systems too quite easily.
(BTW: your implementation of that is really nice).

**Comment by antonfirsov** [comment] 2023-03-27 15:51
I can confirm this. There are 133 failing tests going scalar-only. For example, this is the output when decoding `testorig12.jpg`:

![DecodeBaselineJpeg_Rgb24_testorig12](https://user-images.githubusercontent.com/6835152/227992792-c39ad1ff-e6c0-4629-9ab1-3f8403eba77e.png)

I recommend fixing these one-by-one, adding the missing test cases for each individual bug in the process.

While `FeatureTestRunner` is good tool, using it systematically in integration tests would be very expensive. I think adding one test leg to cover the scalar case on one OS, as https://github.com/SixLabors/ImageSharp/issues/2414#issuecomment-1484109231 suggests, would be valuable.

**Comment by antonfirsov** [comment] 2023-03-27 20:48
No, this image is YCbCr, looks like we have a lot of lurking bugs.

**Comment by br3aker** [comment] 2023-03-29 06:27
> I can confirm this. I see 133 failing tests going scalar-only on my machine. For example, this is the output when decoding `testorig12.jpg`:
> 
> ![DecodeBaselineJpeg_Rgb24_testorig12](https://user-images.githubusercontent.com/6835152/227992792-c39ad1ff-e6c0-4629-9ab1-3f8403eba77e.png)

Example looks like a zig-zag algorithm error, you've tested those with `FeatureTestRunner`, right?

**Comment by stefannikolei** [comment] 2023-03-29 15:33
I went a bit back in history and could identify the problematic PR which introduced this error.

What I know so far is that the tests are failing after #2076 got merged

**Comment by brianpopow** [comment] 2023-03-31 07:42
Now on the main branch there are 39 failing tests left for dotnet6.0 and it seems
some of them are not present in dotnet7.0.

The difference seem to come from png test which have text chunks and call `Latin1Encoding.GetString()`. 
Stack trace (shortend for brevity):
```
Message:
System.PlatformNotSupportedException : Operation is not supported on this platform.

      Stack Trace: 
Sse2.LoadScalarVector128(UInt64* address)
Latin1Utility.WidenLatin1ToUtf16_Sse2(Byte* pLatin1Buffer, Char* pUtf16Buffer, UIntPtr elementCount)
<>c.<GetString>b__29_0(Span`1 chars, ValueTuple`2 args)
String.Create[TState](Int32 length, TState state, SpanAction`2 action)
Latin1Encoding.GetString(Byte[] bytes)
PngDecoderCore.TryUncompressTextData
```

Other failing tests are tiff images which use jpeg compression, example:

![TiffDecoder_CanDecode_JpegCompressed_Rgba32_Issue2123](https://user-images.githubusercontent.com/38701097/229056215-0d747d14-64c0-4deb-a975-a7e542e29521.png)


Other failing tests seems to have something todo with resizing, for example `GifDecoder_Decode_Resize`
does not match expectation by a small amount (Total difference: 0,0001%)

**Comment by br3aker** [comment] 2023-04-02 13:42
I've found a nasty bug, not related to the color converter pipeline.
PR is in the works.

**Comment by br3aker** [comment] 2023-04-02 16:44
Test run with `DOTNET_EnableSSE=0` for linked PR build:

![image](https://user-images.githubusercontent.com/20967409/229366760-63591e3a-fc7e-481e-82dc-7f2ebbbe87f3.png)

All jpeg tests are passing now.

**Comment by brianpopow** [comment] 2023-04-02 16:51
> All jpeg tests are passing now.

@br3aker thanks for looking into this issue!

**Comment by JimBobSquarePants** [comment] 2023-04-05 22:45
The only way to avoid closing is not to use the [closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) when linking to issues.

**Comment by brianpopow** [comment] 2023-04-23 15:37
I cant figure out what's going wrong with those png encoder tests. As mentioned [above](https://github.com/SixLabors/ImageSharp/issues/2414#issuecomment-1491455526) those failing tests seem to be related to decoding text chunks.

Here is an example stack trace from ` PngEncoderTests.Chunks.cs`:

```
Message: 
System.PlatformNotSupportedException : Operation is not supported on this platform.

      Stack Trace: 
Sse2.LoadScalarVector128(UInt64* address)
Latin1Utility.WidenLatin1ToUtf16_Sse2(Byte* pLatin1Buffer, Char* pUtf16Buffer, UIntPtr elementCount)
<>c.<GetString>b__29_0(Span`1 chars, ValueTuple`2 args)
String.Create[TState](Int32 length, TState state, SpanAction`2 action)
Latin1Encoding.GetString(Byte[] bytes)
PngDecoderCore.TryUncompressTextData(ReadOnlySpan`1 compressedData, Encoding encoding, String& value) line 1385
PngDecoderCore.ReadCompressedTextChunk(ImageMetadata baseMetadata, PngMetadata metadata, ReadOnlySpan`1 data) line 1065
PngDecoderCore.Decode[TPixel](BufferedReadStream stream, CancellationToken cancellationToken) line 195
ImageDecoderUtilities.Decode[TPixel](IImageDecoderInternals decoder, Configuration configuration, Stream stream, Func`3 largeImageExceptionFactory, CancellationToken cancellationToken) line 57
ImageDecoderUtilities.Decode[TPixel](IImageDecoderInternals decoder, Configuration configuration, Stream stream, CancellationToken cancellationToken) line 43
PngDecoder.Decode[TPixel](DecoderOptions options, Stream stream, CancellationToken cancellationToken) line 38
<>c__DisplayClass0_0`1.<Decode>b__0(Stream s) line 23
ImageDecoder.<WithSeekableStream>g__PeformActionAndResetPosition|11_0[T](Stream s, Int64 position, <>c__DisplayClass11_0`1& ) line 194
ImageDecoder.WithSeekableStream[T](DecoderOptions options, Stream stream, Func`2 action) line 209
ImageDecoder.Decode[TPixel](DecoderOptions options, Stream stream) line 20
Image.Decode[TPixel](DecoderOptions options, Stream stream) line 122
<>c__DisplayClass84_0`1.<Load>b__0(Stream s) line 234
Image.WithSeekableStream[T](DecoderOptions options, Stream stream, Func`2 action) line 301
Image.Load[TPixel](DecoderOptions options, Stream stream) line 234
Image.Load[TPixel](DecoderOptions options, ReadOnlySpan`1 data) line 139
Image.Load[TPixel](ReadOnlySpan`1 data) line 120
TestFile.CreateRgba32Image() line 110
PngEncoderTests.Chunk_ComesBeforeIDat(Object chunkTypeObj) line 115
```

The weird thing is, when I execute a single failing test, the test runs fine and is green.

**Comment by br3aker** [comment] 2023-04-23 22:03
Wild guess: maybe tiered compilation (rejitter?) doesn't respect ISA environmental variables on net6? Didn't check on net7.

I've set this env variable `DOTNET_TieredCompilation=0` and got following results:
![image](https://user-images.githubusercontent.com/20967409/233868153-3a4b7a93-e385-4406-88e8-fd06d231d26b.png)

Last failing test is related to image diff threshold, not sure whether it's related to the codegen.

Now I'm completely lost, we can't simply set this variable and go on - there's a probability it can be broken by some R2R situation? Sorry to bother you @tannergooding but I'm not sure we can solve this on our own :)

**Comment by tannergooding** [comment] 2023-04-24 15:35
Could I get a few more details on exactly what's being set and what OS/architecture you're running on?

**Comment by br3aker** [comment] 2023-04-24 17:31
> what OS/architecture you're running on

Win11/x86, no emulation

> what's being set

We are trying to test all ImageSharp tests for scalar path so I've set `<DOTNET_EnableSSE>0</DOTNET_EnableSSE>` in `.runsettings` for emulating cpu without sse support at all. 

We go some flaky tests which end up throwing `System.PlatformNotSupportedException : Operation is not supported on this platform.`, if these tests are executed among other tests - everything breaks due to this call: `Sse2.LoadScalarVector128(UInt64* address)` from `mscorlib`, you can check exact stacktrace from the message above mine.
But if these flacky tests are launched in isolation - they successfully pass. I immediately thought about tiered jitting and decided to turn it off with `<DOTNET_TieredCompilation>0</DOTNET_TieredCompilation>` in `.runsettings` file, file looked like this:

```
<?xml version="1.0" encoding="utf-8" ?>
<RunSettings>
    <RunConfiguration>
        <DOTNET_EnableSSE>0</DOTNET_EnableSSE>
        <DOTNET_TieredCompilation>0</DOTNET_TieredCompilation>
    </RunConfiguration>
</RunSettings>
```
With this settings flaky tests do not fail, i.e. no more `System.PlatformNotSupportedException` from SSE calls.

**Comment by tannergooding** [comment] 2023-04-24 17:37
This sounds like a bad interaction between `EnableSSE=0` and `ReadyToRun`. Does setting `DOTNET_ReadyToRun=0` fix it?

**Comment by br3aker** [comment] 2023-04-24 18:48
Yep, setting `DOTNET_ReadyToRun=0` fixed tests. Should we open an issue or it's intended/workaround exists?

**Comment by tannergooding** [comment] 2023-04-24 18:51
Please open an issue. I'm pretty sure I know what the issue is, but would be good to get it tracked explicitly as impacting the broader community

**Comment by br3aker** [comment] 2023-04-24 18:53
Got it, will do tomorrow, thank you for the help!

**Comment by JimBobSquarePants** [comment] 2023-11-09 11:14
I think we can go ahead and close this now that the upstream issue is fixed in .NET 7+

**Closed by JimBobSquarePants** 2023-11-09 11:14 UTC
Labels: bug, unit tests
