### ISSUE TITLE
.NET Standard issues on .NET Framework 4.7.1

### ISSUE THREAD

**Issue by Latency** [SixLabors/ImageSharp#433] opened 2018-01-13 19:11 UTC
### Prerequisites

> Image.Load() => {"Could not load file or assembly 'System.Runtime, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.":"System.Runtime, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a"}

My project can be found on my github [here](https://github.com/Latency/Hearthstone-Deck-Tracker).

- [Reference] [#567](https://github.com/dotnet/standard/issues/567)

### Description
I am just trying to run it as native 4.7.1 without CORE for Main UI.. I have my dependancy libs x-targeted for both Core2.0 and 4.7.1 but that shouldnt do anything. Im sure the problem is with ImageSharp pack v1.0.0-beta002 (latest)..

Because I didn't have any problems prior to installation the issue is I need to not have a binding redirect from the package from System.Runtime. It is now integrated as part of STD.

System.Runtime from NuGet package (latest) installation targets 4.6.2. It is incompatible and will not load if copied. In fact, if you Browse to include it as a referenced assembly, you get a yellow exclamation box. More than likely, conflicting or incompatible.

I am thinking the only thing I know how to do is revert to stable package 1.5 but thats 6 mo old and the constructs are different for things.

### Steps to Reproduce
As workaround, I was able to include this library from Reference assemblies and then under Properties, change the alias to "newVer" or whatever you wish.

Then in your project in the source code, you need to add:
`extern alias newVer;`

Where you then pre-pend the namespace like so.

`using (var zip = ZipFile.Open(backupFilePath, newVer::System.IO.Compression.ZipArchiveMode.Create)) { ... }`

This will not work for System.Runtime since there is not one to be found in Reference assemblies anymore.

### Solution

I will try to download the src and repack it today against v4.7.1 but I would also like to mention:
_**System.IO.Compression**_ should be added to the [#567](https://github.com/dotnet/standard/issues/567).

### System Configuration

- ImageSharp version:  1.0.0.0beta-002
- Other ImageSharp packages and versions:  N/A
- Environment (Operating system, version and so on):  Windows 10 Pro v1709 (Creators Build)
- .NET Framework version:  .NET Framework 4.7.1  + .NET Core 2.0
- Additional information:  Intel I-7 4700MQ  32Gb x64

**Comment by antonfirsov** [comment] 2018-01-13 19:42
@Latency I'm not able to build your project, half of the solution is reported being missing. 

Installing and using ImageSharp in an empty `4.7.1` project works perfectly for me! Have you tried cleaning/reinstalling your NuGet stuff?

**Comment by tocsoft** [comment] 2018-01-13 19:55
I concur I have no problem installing ImageSharp in a new 4.7.1 project in either csproj based `PackageReference` or the older `packages.config` style of reference. 

Like @antonfirsov I also can't get the project to run.. even after running the bootstrap.bat and even trying to build all the projected individually.

**Comment by JimBobSquarePants** [comment] 2018-01-13 22:56
I'm adding a link here to a Windows classic desktop app targeting NET 4.7.1 running beta 2 built using VS 15.5.3

I'm able to resize a png (thus touching compression at runtime) without issue.

https://1drv.ms/u/s!AhWs_teP7rZGwdMRLgclPUcb4E4mMA

**Comment by JimBobSquarePants** [comment] 2018-01-14 03:03
Here's another console app this time targeting both NetCore 2.0 and NetFramework 4.7.1

https://1drv.ms/u/s!AhWs_teP7rZGwdMbfM4EwwueQkiCow

**Comment by Latency** [comment] 2018-01-14 12:09
Yes, there are 4 projects split up in HearthSim to make this one work.
I have bundled everything together to replicate in this zip file [here](https://github.com/Latency/Hearthstone-Deck-Tracker/blob/master/Hearthstone-Deck-Tracker.zip).

I have confirmed that in fact it IS the build and release from your package.
After spending a day to repack it.. It is now working as the dependencies and reference assemblies are resolved correctly.

**Comment by antonfirsov** [comment] 2018-01-14 12:34
@Latency your bundled solution works perfectly for me! Looks like, the problem is related to your environment. Might be a .NET Framework / .NET Standard issue. I suggest to ask for help on Microsoft forums.

Please check out our latest comments on gitter and #434! We are not going to accept your PR-s.

**Comment by tocsoft** [comment] 2018-01-14 13:03
I'm closing this as can't reproduce. If you believe this is closed in error please provide a simpler solution/project that reproduces the error.

**Closed by tocsoft** 2018-01-14 13:03 UTC

**Comment by copernicus365** [comment] 2018-04-22 19:37
No, this should NOT be closed, there are tons of such problems with net 4.7.1 inconsistencies causing build or runtime errors of this sort. I've been unable to update multiple projects to full net framework 4.7.1 because of these issues for months and months, after many extremely painful failed attempts to do so. I can't believe this has not been fixed yet, and that there is no movement on this issue! The whole net team should stop there work and make sure to remove these dll hell inconsistencies between the full framework, especially with 4.7.1. For instance, this problem is not just with System.Runtime, it is also with System.Net.Http, it seems as soon as you upgrade from a lower full framework (in my case from net 4.6.1) to 4.7.1, suddenly it's like the framework is expecting references to the nuget System.Net.Http, which would be fine, except that any dependencies, anywhere, that ever reference a full framework version of System.Net.Http, cause non-compilable errors at build time.

**Comment by JimBobSquarePants** [comment] 2018-04-22 21:02
Nice unwelcome rant but what has this got to do with our library and immediate issue?

**Comment by tocsoft** [comment] 2018-04-23 08:10
@copernicus365 then like I said in my reason for closure, instead of ranting unhelpfully, please provide a verifiable reproduction of the original issue and I would be happy to reopen the ticket. But **note** this will stay closed as 'Can reproduce' until the development team (who have made this library in our free time, and thus have no obligation to fix any issues raised at all) can reproduce the problem (and thus can try and fix it).

If on the other hand you are complaining about the way .Net Standard targeted libraries are installed into full framework projects then that's an issue with nuget/dotnet as a framework and not an issue with a single library, then I suggest you raise your concerns with Microsoft instead of an independent dev team who have no control over these things.

**Comment by copernicus365** [comment] 2018-04-23 11:46
Sorry guys, I missed that this was not one of the netfx repos. It does come up as one of the top hits on google for net 4.7.1 problems, and the title is worded well for that, but again, missed it's on a specific library. Cheers
