### ISSUE TITLE
Webp Image failing to compress properly

### ISSUE THREAD

**Issue by BowserKingKoopa** [SixLabors/ImageSharp#2216] opened 2022-08-28 00:28 UTC
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have verified that I am running the latest version of ImageSharp
- [X] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [X] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### ImageSharp version

2.1.3

### Other ImageSharp packages and versions

n/a

### Environment (Operating system, version and so on)

Windows 10

### .NET Framework version

.NET 6

### Description

My Webp Image with transparency fails to compress properly.

### Steps to Reproduce

My Webp images fail to compress properly. 

```
var img = Image.Load<Rgba32>("12.png");
var encoder = new WebpEncoder()
{
    UseAlphaCompression = true,
    FileFormat = WebpFileFormatType.Lossy,
    FilterStrength = 60,
    Method = WebpEncodingMethod.Level4,
    Quality = 75,
};
img.SaveAsWebp("12.webp", encoder);
```

This takes my 2MB PNG and produces a 4MB Webp. Sqoosh.app, for comparison, produces a 240kb image with near identical settings.

Things I've noticed that might be the problem.
1. It seems to have something to do with the transparency.
2. If you uncheck 'Compress alpha' in Sqoosh you get a 4MB file which is the same size ImageSharp is producing.
3. The description of the UseAlphaCompression property on the WebpEncoder class makes it sound like it only works for Lossless compression mode. So theory: AlphaCompression is not being done in Lossy mode and that's why the file sizes come out huge.
4. If I change to Lossless format I get a 1.5MB file. Better than the 4MB Lossy version.

So I think it's not doing alpha compression. Is there a setting somewhere I missed in order to get the results I'm expecting?

### Images

![12](https://user-images.githubusercontent.com/11095411/187052364-b88837f4-65d2-405e-9004-58237afcdd4e.png)

**Comment by brianpopow** [comment] 2022-08-28 10:41
This seems to be a duplicate of #2171. Can you try our [nightly build](https://www.myget.org/feed/sixlabors/package/nuget/SixLabors.ImageSharp) to confirm?

**Comment by BowserKingKoopa** [comment] 2022-08-28 14:34
> This seems to be a duplicate of #2171. Can you try our [nightly build](https://www.myget.org/feed/sixlabors/package/nuget/SixLabors.ImageSharp) to confirm?

Yes you are right. That nightly build fixes the issue. ImageSharp produces a beautiful 240k image just like Sqoosh. Awesome. Thank you so much.

**Closed** 2022-08-28 14:38 UTC
Labels: duplicate, formats:webp
