### ISSUE TITLE
Error load TIFF file from byte array

### ISSUE THREAD

**Issue by dfornero** [SixLabors/ImageSharp#2113] opened 2022-05-10 22:31 UTC
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have verified that I am running the latest version of ImageSharp
- [X] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [X] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### ImageSharp version

2.1.1

### Other ImageSharp packages and versions

2.1.1

### Environment (Operating system, version and so on)

Windows 10

### .NET Framework version

Net Core 3.1

### Description

Hello to everyone; I'm newbie working with images; sometimes I got an error loading an image (tiff format), from an array of bytes; sometimes it works ok. The message error is "Images with different sizes are not supported".  I tried to find out a clue to resolve the error, but no way. Any suggestion? Thanks a lot!!

### Steps to Reproduce

byte[] tiffImage = GetImageFromBytes(); // this load the array with one image from a database
using (Image<Rgba32> img = Image.load<Rgba32>(tiffImage);
{
}

**Comment by brianpopow** [comment] 2022-05-11 09:26
The error message: `Images with different sizes are not supported` states already the problem: Tiff images can contain frames with different sizes, which we do not support yet. Only frames with the same size, see [Discussion](https://github.com/SixLabors/ImageSharp/discussions/1982)

The best workaround for that for now is to only decoding the first frame:
```
Image.Load(@"image.tiff",
new TiffDecoder()
{
    DecodingMode = FrameDecodingMode.First
});
```

Usually those images are different resolutions of the same image, so you could manually resize the image then, if you need it.

I am closing this, since it's not a bug.

**Closed by brianpopow** 2022-05-11 09:26 UTC
Labels: needs triage
