### ISSUE TITLE
PNG gets decoded incorrectly on Mono

### ISSUE THREAD

**Issue by TodesBrot** [SixLabors/ImageSharp#598] opened 2018-05-29 17:01 UTC
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have verified that I am running the latest version of ImageSharp
- [X] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [X] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
The image below gets decoded incorrectly on Mono.
![second](https://user-images.githubusercontent.com/8228822/40673083-0108b4ec-6371-11e8-82e3-7ef11570b37b.png)

It gets loaded correctly on Windows, but on Mono the bottom is transparent.
![output](https://user-images.githubusercontent.com/8228822/40673148-331b3b8a-6371-11e8-8452-c34d93842435.png)

This bug seems to be similar to #223.

I have confirmed this bug on Android 8 and on Ubuntu 16.04 using the Linux Subsystem for Windows.

### Steps to Reproduce
Load the first image in a Mono environment.

### System Configuration
Android 8.0.0 running Mono
Ubuntu 16.04 running Mono, using the Linux Subsystem for Windows

- ImageSharp version: v1.0.0-beta0004
- Other ImageSharp packages and versions:
- Environment (Operating system, version and so on): Android 8.0.0, Ubuntu 16.04
- .NET Framework version: Mono
- Additional information:

**Comment by Splamy** [comment] 2018-08-08 00:46
I'm experiencing the same problem. Took me half a day but I think I got it...

The problem is a slightly different behavior in net/dotnet and mono `DeflateStream`
The following code will execute differently:
```csharp
using System;
using System.IO;
using System.IO.Compression;
using System.Text;

namespace Bug1
{
    internal class Program
    {
        public static void Main(string[] args)
        {
            // "HelloWorld" as UTF8/DeflateStream(...,CompressionMode.Compress)
            var buffer = new byte[] { 243, 72, 205, 201, 201, 15, 207, 47, 202, 73, 1, 0 };
            var mem = new MemoryStream(buffer);
            var chu = new ChunkedReader(mem);
            var def = new DeflateStream(chu, CompressionMode.Decompress);
            
            var buffer2 = new byte[4096];
            int read2 = 0;

            chu.limit = 3;
            read2 += def.Read(buffer2, read2, buffer2.Length - read2);
            chu.limit = 100;
            read2 += def.Read(buffer2, read2, buffer2.Length - read2);

            var res = Encoding.UTF8.GetString(buffer2, 0, read2);
            Console.WriteLine(res);
        }
    }   
    
    public class ChunkedReader : Stream
    {
        private int sum = 0;
        public int limit = 0;
        private string name;
        private Stream baseStream;
        
        public ChunkedReader(Stream baseStream, string name = null)
        {
            this.baseStream = baseStream;
            this.name = name;
        }

        public override void Flush()
        {
            this.baseStream.Flush();
        }

        public override int Read(byte[] buffer, int offset, int count)
        {
            int read;
            read = this.baseStream.Read(buffer, offset, Math.Min(count, this.limit));
            sum += read;
            this.limit -= read;
            Console.WriteLine("{3}> Sum: {0}, Read {1}, Req: {2}", this.sum, read, count, name ?? "XXX");
            return read;
        }

        public override long Seek(long offset, SeekOrigin origin)
        {
            return this.baseStream.Seek(offset, origin);
        }

        public override void SetLength(long value)
        {
            this.baseStream.SetLength(value);
        }

        public override void Write(byte[] buffer, int offset, int count)
        {
            this.baseStream.Write(buffer, offset, count);
        }

        public override bool CanRead => this.baseStream.CanRead;

        public override bool CanSeek => this.baseStream.CanSeek;

        public override bool CanWrite => this.baseStream.CanWrite;

        public override long Length => this.baseStream.Length;

        public override long Position
        {
            get => this.baseStream.Position;
            set => this.baseStream.Position = value;
        }
    }
}
```

While under net/dotnet it will print
```
XXX> Sum: 3, Read 3, Req: 8192
XXX> Sum: 3, Read 0, Req: 8192
XXX> Sum: 12, Read 9, Req: 8192
HelloWorld
```

Under mono it will refuse to continue reading after it once got `0` and only print
```
XXX> Sum: 3, Read 3, Req: 4096
XXX> Sum: 3, Read 0, Req: 4096
He
```

The problem affects png files which have more than 1 `IDAT` block.
The first block will end, Read will return 0 and the following blocks all won't be read anymore.

**Comment by antonfirsov** [comment] 2018-08-08 09:50
@Splamy thanks a lot for taking the time to investigate this!

We probably should [raise a mono issue](https://github.com/mono/mono/issues) (again!), and implement a workaround within our codebase.

**Comment by JimBobSquarePants** [comment] 2018-08-11 10:35
@Splamy top notch work, Well done! 👍 

I just had a look at the Mono issue tracker and the issue hasn't been raised there so I will go ahead and copy your issue across there. Hopefully they can provide a workaround because I cannot see one. 

Do you have the Mono version?

**Comment by Splamy** [comment] 2018-08-11 12:54
Sure thing, I tested it locally on Arch Linux with:
```
Mono JIT compiler version 5.12.0 (makepkg/58637d0ee7c Wed Jun  6 22:41:15 CEST 2018)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           __thread
	SIGSEGV:       altstack
	Notifications: epoll
	Architecture:  amd64
	Disabled:      none
	Misc:          softdebug 
	Interpreter:   yes
	LLVM:          supported, not enabled.
	GC:            sgen (concurrent by default)
```
My server is running Ubuntu 16.04 with `Mono JIT compiler version 5.12.0.301 (tarball Wed Jul 25 15:47:18 UTC 2018)` (rest same) Where the problem is the same.

**Comment by JimBobSquarePants** [comment] 2018-08-21 08:55
Looks like Mono will be porting in CoreFX code

https://github.com/mono/mono/issues/6974

**Comment by baulig** [comment] 2018-08-27 13:17
Well, I would argue that your test case is relying on a broken behavior in dotnet.

What's happening here is that on the second call to your `ChunkedReader.Read()`, you are returning 0.  Getting a 0 return from a `Read()` call in general means end-of-stream, so `DeflateStream` should not attempt any more reads.  However, it should probably throw an exception as well because it didn't receive all the data.

We need to figure out why the underlying `Read()` call returns 0.  How do you load those PNG files, do you have a full test case with ImageShark?  What's the inner stream that's being used by `DeflateStream` and where does it come from?

**Comment by Splamy** [comment] 2018-08-27 13:34
I can shortly explain why the underlying stream returns 0.
PNG allows to split up the complete compressed data into blocks. Which means each png will consist of 1-n `IDAT` blocks which contain data.
The ZlibInflateStream gets called to only read the current data block: https://github.com/SixLabors/ImageSharp/blob/master/src/ImageSharp/Formats/Png/Zlib/ZlibInflateStream.cs#L88
While the parent stream afterwards still can be read for control data: https://github.com/SixLabors/ImageSharp/blob/master/src/ImageSharp/Formats/Png/PngDecoderCore.cs#L249

Imo this is actually, while maybe a bit tangled logic, a elegant solution as it requires no additional buffering when decompressing the inner data.

**Comment by baulig** [comment] 2018-08-27 13:40
Well, as I just explained in https://github.com/mono/mono/issues/10054, I think that too much code in Mono relies on the assumption that `Read()` returning 0 means "end of stream" and that "end of stream" is permanent.

I'm not sure what a good solution for this problem would be.  Maybe we could just take `DeflateStream` from CoreFX and see whether that fixes the problem.

**Comment by filipnavara** [comment] 2018-08-27 13:46
> Maybe we could just take DeflateStream from CoreFX and see whether that fixes the problem.

I was looking into it (due to other issues with disposing of DeflateStream), but there's some cleanup going on right now in the CoreFX repository, so it may not be the best time. Additionally it will need some input on how to address WebAssembly since it relies on pinvokes to the native library. Apparently the original managed code implementation is being removed [from CoreFX].

**Comment by Splamy** [comment] 2018-08-27 15:31
I've added
<details>
```csharp
        public void AllocateNewBytes(int bytes)
        {
            Debug.WriteLine("ZlibInflateStream registered: {0}", bytes);
            this.currentDataRemaining = bytes;
            if (this.compressedStream == null)
            {
                this.InitializeInflateStream();
            }
        }
```
https://github.com/SixLabors/ImageSharp/blob/master/src/ImageSharp/Formats/Png/Zlib/ZlibInflateStream.cs#L88-L95

```csharp
        public override int Read(byte[] buffer, int offset, int count)
        {
            Debug.WriteLine("ZlibInflateStream Read: {0}", count);
            if (this.currentDataRemaining == 0)
            {
                return 0;
            }

            int bytesToRead = Math.Min(count, this.currentDataRemaining);
            this.currentDataRemaining -= bytesToRead;
            return this.innerStream.Read(buffer, offset, bytesToRead);
        }
```
https://github.com/SixLabors/ImageSharp/blob/master/src/ImageSharp/Formats/Png/Zlib/ZlibInflateStream.cs#L111-L121

```csharp
this.compressedStream = new DeflateStream(new TrackingStream(this, "zlibreader"), CompressionMode.Decompress, true);
```
https://github.com/SixLabors/ImageSharp/blob/master/src/ImageSharp/Formats/Png/Zlib/ZlibInflateStream.cs#L224

(Where TrackingStream is just a Stream wrapper which counts everything)
</details>
  
  
And this is the output
<details>
```
ZlibInflateStream registered: 65535
ZlibInflateStream Read: 4096
zlibreader> Sum: 4096, Read 4096, Req: 4096
ZlibInflateStream Read: 4096
zlibreader> Sum: 8192, Read 4096, Req: 4096
ZlibInflateStream Read: 4096
zlibreader> Sum: 12288, Read 4096, Req: 4096
ZlibInflateStream Read: 4096
zlibreader> Sum: 16384, Read 4096, Req: 4096
ZlibInflateStream Read: 4096
zlibreader> Sum: 20480, Read 4096, Req: 4096
ZlibInflateStream Read: 4096
zlibreader> Sum: 24576, Read 4096, Req: 4096
ZlibInflateStream Read: 4096
zlibreader> Sum: 28672, Read 4096, Req: 4096
ZlibInflateStream Read: 4096
zlibreader> Sum: 32768, Read 4096, Req: 4096
ZlibInflateStream Read: 4096
zlibreader> Sum: 36864, Read 4096, Req: 4096
ZlibInflateStream Read: 4096
zlibreader> Sum: 40960, Read 4096, Req: 4096
ZlibInflateStream Read: 4096
zlibreader> Sum: 45056, Read 4096, Req: 4096
ZlibInflateStream Read: 4096
zlibreader> Sum: 49152, Read 4096, Req: 4096
ZlibInflateStream Read: 4096
zlibreader> Sum: 53248, Read 4096, Req: 4096
ZlibInflateStream Read: 4096
zlibreader> Sum: 57344, Read 4096, Req: 4096
ZlibInflateStream Read: 4096
zlibreader> Sum: 61440, Read 4096, Req: 4096
ZlibInflateStream Read: 4096
zlibreader> Sum: 65533, Read 4093, Req: 4096
ZlibInflateStream Read: 4096
zlibreader> Sum: 65533, Read 0, Req: 4096
ZlibInflateStream registered: 43423
```
</details>

If i didn't make any mistakes gets the correct lengths: 65535, 43423

**Comment by TodesBrot** [comment] 2018-08-31 17:45
This is probably related, I found out that the image below can't get decoded on Mono, it throws "System.NotSupportedException: Image cannot be loaded."
![rain](https://user-images.githubusercontent.com/8228822/44927876-59c9f300-ad56-11e8-8bc4-eabca81e9438.png)

**Comment by JimBobSquarePants** [comment] 2018-08-31 17:47
@TodesBrot No, that'll be a stream issue. The error is thrown when a format cannot be established.

**Comment by TodesBrot** [comment] 2018-08-31 17:54
@JimBobSquarePants ...You're right, stupid error on my part. Sorry.

**Comment by JimBobSquarePants** [comment] 2018-08-31 18:02
No worries, Happens all the time 😄

**Comment by JimBobSquarePants** [comment] 2018-09-13 15:39
Closing this now Mono have fixed it. 

https://github.com/mono/mono/pull/10329

**Closed by JimBobSquarePants** 2018-09-13 15:39 UTC
Labels: help wanted, platform:mono
