### ISSUE TITLE
.Net 5.0 RC-1 breaks ImageSharp

### ISSUE THREAD

**Issue by lofcz** [SixLabors/ImageSharp#1356] opened 2020-09-16 16:15 UTC
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of ImageSharp
- [x] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
I've encountered a strange bug when mutating images after migrating mvc app from net fw48 to net5 rc1. I've swapped to async image handling. Steps I do (async action on a controller):

```csharp
1) await HttpContext.Request.ReadFormAsync()
2) Image<Rgba32> img = Image.Load<Rgba32>([first image from form].OpenReadStream(), out IImageFormat imgFormat);
3) await img.SaveAsync("some path"); // saves the image correctly
4) img.Mutate(x => x.Resize(w, h, s)); // thumbnail; used Bicubic, tried Lancoz3 to check if that could be the problem
5) await img.SaveAsync("thumbnail path");

// also tried alternative
5) await using FileStream stream = System.IO.File.Create("some path");
6) await img.SaveAsync(stream, imgFormat);
```

Extremely frustrating is that this is happening only on production, not on my local machine. I've tried to use another sampler and use latest dev build of ImageSharp, neither helped. In each and every case the first half of an image is mutated correctly, while the other is either blank or filled with artifacts. I'm clueless about how should I move forward, the only option so far would be to go back to sync processing of images which I'd very much like to avoid. Attaching some test images:

Saved thumbnail 1:

![a8f3fce0-c6ec-4e4b-a304-ae381301f9ef_thumbnail (1)](https://user-images.githubusercontent.com/10260230/93362791-b8cc0900-f846-11ea-9d39-9cd75aeb2d13.png)

Saved non-mutated image 1:

![a8f3fce0-c6ec-4e4b-a304-ae381301f9ef](https://user-images.githubusercontent.com/10260230/93362884-d5684100-f846-11ea-852a-b3735e5503a7.png)

Saved thumbnail 2:

![803238f6-8248-4df7-ac73-a0f36840295a_thumbnail](https://user-images.githubusercontent.com/10260230/93362977-edd85b80-f846-11ea-886d-6f58d199a1ba.png)

Saved non-mutated image 2:

![803238f6-8248-4df7-ac73-a0f36840295a](https://user-images.githubusercontent.com/10260230/93363019-f9c41d80-f846-11ea-9984-0742551e9a61.png)

Saved thumbnail 3:

![bc54f22d-1ae8-4135-ad38-3f3e761767f4_thumbnail](https://user-images.githubusercontent.com/10260230/93363105-15c7bf00-f847-11ea-9b37-f9fa7f3807f8.png)

Saved non-mutated image 3:

![bc54f22d-1ae8-4135-ad38-3f3e761767f4](https://user-images.githubusercontent.com/10260230/93363130-1fe9bd80-f847-11ea-8613-48c82cba61b7.png)

### System Configuration
- dev: windows 10 20206_rsprerelease, net5 rc1
- production: windows server 2016 datacenter 10.0.14393, net5 rc1

### ImageSharp version:
- tried 1.1, then 1.0.2 alpha 7

**Comment by JimBobSquarePants** [comment] 2020-09-16 19:23
It's hard to be sure by reading from your code sample but it looks to me like you are not disposing of your input stream nor the image.

``` c#
Image<Rgba32> img = Image.Load<Rgba32>([first image from form].OpenReadStream(), out IImageFormat imgFormat);
```

Should be.

``` c#
using Stream inputStream = [first image from form].OpenReadStream();
using Image<Rgba32> img = Image.Load<Rgba32>(inputStream, out IImageFormat imgFormat);
```
In the case of Image, the GC would collect everything eventually but it's wasteful so you should always dispose after using. 
The stream though must be disposed of to ensure the content is all written from any internal buffers.

**Comment by lofcz** [comment] 2020-09-16 20:00
@JimBobSquarePants thanks, I've noticed that when I clone the image and then mutate the clonned copy it works properly both on dev and prod. Couldn't that be caused by `ConfigureAwait(false)` ImageSharp is using when processing async save?

**Comment by JimBobSquarePants** [comment] 2020-09-16 20:19
I couldn't tell you. Could you please post a complete sample so that we can correctly replicate and diagnose any issues.

**Comment by klogeaage** [comment] 2020-09-27 19:27
I can confirm this issue, which started occurring after I upgraded from Net Core 3.1 to 5.0 RC1. I am NOT using the async variants of the ImageSharp methods, except the controller if of course async, and I believe I am using/disposing of `Image `and `Streams `correctly. Going back to .Net Core 3.1 fixed the issue, but of course I would also like to move to 5.0.

**Comment by JimBobSquarePants** [comment] 2020-09-27 19:29
I’ll need a means to replicate the issue. Without one nothing happens.

**Comment by klogeaage** [comment] 2020-09-27 19:29
Sure, I'll see if I can replicate in some unit tests.

**Comment by JimBobSquarePants** [comment] 2020-09-27 19:30
Thanks. That would be incredibly helpful!

**Comment by klogeaage** [comment] 2020-09-27 20:24
Argh, it's working fine in an Xunit test with just the imaging and stream operations :-(

**Comment by klogeaage** [comment] 2020-09-27 20:45
And the code (fragment) that is not working in .Net 5.0 RC1:

    var imageResizer = new ImageProcessor();
    // Build low-resolution version as well
    using (MemoryStream lowResStream = imageResizer.ResizeTo(destinationStream, ImageProcessor.LowResWidth))
    {
        await _blobStorageClient.UploadAsync(file.FileName, file.ContentType, lowResStream, blobId + 
            ImageProcessor.LowResExtension);
        _logger.LogInformation($"Uploaded low-res image of {blobId}.");
    }

All quite simple, I think. Very strange...

**Comment by JimBobSquarePants** [comment] 2020-09-27 20:56
I’m assuming you confirmed that the issue isn’t with the Azure upload by saving the output to the file system before uploading?

**Comment by klogeaage** [comment] 2020-09-27 21:01
No, I haven't, but it is uploading the original image as well as video and sound files with no issues, so I don't think there is an issue with that. Also, the Azure blob storage libraries are used extensively in many applications so any problem with those is likely to be reported and fixed very quickly.

**Comment by klogeaage** [comment] 2020-09-27 21:11
@lofcz Could you please elaborate a little on the workaround you mentioned with Cloning the image?

**Comment by JimBobSquarePants** [comment] 2020-09-27 21:18
It’s best to check just to rule out any possibilities.

What is `ImageProcessor`?

**Comment by klogeaage** [comment] 2020-09-27 21:42
`ImageProcessor `is simply my encapsulation of your library, i.e. it is a service class for the controller. Here it is:

```
using SixLabors.ImageSharp;
using SixLabors.ImageSharp.Metadata.Profiles.Exif;
using SixLabors.ImageSharp.Processing;
using System.IO;

namespace JourneyDoc.API.Services
{
    public class ImageProcessor
    {
        public const string LowResExtension = ".low";
        public const int LowResWidth = 700;
        public const int DefaultQuality = 90;

        public MemoryStream ResizeTo(Stream input, int width)
        {
            var output = new MemoryStream();
            input.Seek(0, SeekOrigin.Begin);
            using Image image = Image.Load(input);
            image.Mutate(x => x.Resize(width: width, 0));
            image.SaveAsJpeg(output);
            output.Seek(0, SeekOrigin.Begin);
            input.Seek(0, SeekOrigin.Begin);
            return output;
        }

        public Stream ReCompress(Stream input, int quality = DefaultQuality)
        {
            var output = new MemoryStream();
            input.Seek(0, SeekOrigin.Begin);
            using Image image = Image.Load(input);
            image.Mutate(x => x.AutoOrient());
            image.SaveAsJpeg(output, new SixLabors.ImageSharp.Formats.Jpeg.JpegEncoder { Quality = quality });
            output.Seek(0, SeekOrigin.Begin);
            input.Seek(0, SeekOrigin.Begin);
            return output;
        }

        /// <summary>
        /// Rotate image so it always is displayed correctly. Workaround for client not doing this.
        /// </summary>
        /// <param name="input"></param>
        /// <returns></returns>
        public Stream AutoOrient(Stream input)
        {
            input.Seek(0, SeekOrigin.Begin);
            using Image image = Image.Load(input);
            IExifValue exifOrientation = image.Metadata?.ExifProfile?.GetValue(ExifTag.Orientation);
            if (exifOrientation?.GetValue() == null || exifOrientation.GetValue().ToString() == "1")
            {
                input.Seek(0, SeekOrigin.Begin);
                return input;
            }
            var output = new MemoryStream();
            image.Mutate(x => x.AutoOrient());
            image.SaveAsJpeg(output, new SixLabors.ImageSharp.Formats.Jpeg.JpegEncoder { Quality = DefaultQuality });
            output.Seek(0, SeekOrigin.Begin);
            input.Seek(0, SeekOrigin.Begin);
            return output;
        }
    }
}

```
I don't use `LoadAsync` or any of the other async methods in ImageSharp, I probably should - do you think it could have a positive effect on this problem? It seems that @lofcz was using them, so know we know it doesn't seem to really influence this issue.

P.S.
It's getting late here in Denmark, so don't expect any immediate response tonight.

**Comment by klogeaage** [comment] 2020-09-28 20:18
I have new information about this problem: it only manifests itself on servers with relatively little memory. I was wondering why I didn't observe the problem in my test environment, which is running on one rather big Azure App Service plan with 7 GB of memory, while the pre-production environment is running on a smaller setup with only 1.75 GB of memory (but more of them to scale out). Turns out that if I scale up the pre-prod environment to a bigger P2V2 App Service with 7 GB of memory, then the problem goes away!

At no point has it reported any out of memory exceptions and .Net Core 3.1 is running fine on the small machines. It may also explain why my unit tests, running on a development machine with 24 GB memory didn't replicate the issue.

The small servers were reporting around 70% max memory usage before the upgrade, and now we are down to 20%, which seems a ridiculously low margin. 

What do you make of that?

**Comment by klogeaage** [comment] 2020-09-28 20:27
Found this rather recent issue that could be relevant: https://developercommunity.visualstudio.com/content/problem/1129949/programs-compiled-with-net-50-use-significantly-mo.html

**Comment by lofcz** [comment] 2020-09-28 22:42
The workaround I've mentioned earlier proved to be unreliable. I've resorted to libvips backend for image processing temporary until this is resolved. @klogeaage

**Comment by klogeaage** [comment] 2020-09-29 07:12
@JimBobSquarePants I think this warrants an issue with .Net 5, but I don't have enough insights into ImageSharp workings to register it.

**Comment by brianpopow** [comment] 2020-09-29 14:53
@klogeaage could you give me the input image you have used or tell me maybe the dimensions? Im trying to reproduce the issue.

**Comment by klogeaage** [comment] 2020-09-29 15:24
@brianpopow I've seen it with many images taken with iOS devices, e.g. 3024 x 4032 in 72 dpi. Example from our garden: 

![20200923_063524549](https://user-images.githubusercontent.com/776718/94578895-84aa0c80-0278-11eb-8306-c80f391eb0c3.jpg)

**Comment by klogeaage** [comment] 2020-09-29 16:10
And this is how it looks when attempting a resize on a server with too little memory:
![72047050-5bf0-4e25-b7bd-0a4133fd1d7d low](https://user-images.githubusercontent.com/776718/94584140-8a0a5580-027e-11eb-81c0-2246feb2aec4.jpg)

While this is the result from a server with exact same configuration, except plenty of memory:
![c3548dde-87e4-4a6a-adc4-046d12776000 low](https://user-images.githubusercontent.com/776718/94584530-0d2bab80-027f-11eb-9b5d-443945017cb7.jpg)

**Comment by brianpopow** [comment] 2020-09-29 16:23
@klogeaage i was able to reproduce it with docker with this image: **mcr.microsoft.com/dotnet/sdk:5.0.100-rc.1**

Here is the branch if someone wants to test it: https://github.com/SixLabors/ImageSharp/tree/bp/Issue1356docker

I have restricted docker to 1 GB and have given it 24 GB, this issue was still there in both cases.

The weird thing is that my resized image looks different:

![garden](https://user-images.githubusercontent.com/38701097/94585740-b6bf6c80-0280-11eb-9497-62fcb63dca8a.jpg)

**Comment by klogeaage** [comment] 2020-09-29 16:27
@brianpopow , Yes, that is weird. Sometimes I feel this wonderful world of it is so complex and unpredictable that it is a miracle anything works...

But really glad you could reproduce the issue, now you just need to find the root cause and fix it, or make a qualified report to Microsoft, of course.

**Comment by JimBobSquarePants** [comment] 2020-09-29 19:37
@brianpopow @klogeaage This is good progress. Now we need to establish whether the issue is with the jpeg decoder/encoder or with the resizer.

**Comment by brianpopow** [comment] 2020-09-29 20:32
@JimBobSquarePants unfortunately its neither. I have tried bmp encoder and png encoder and its the same issue. Also edge detection instead of resizing and still the same issue.

**Comment by JimBobSquarePants** [comment] 2020-09-29 20:34
Eek! Then we have a memory allocation problem!

**Comment by brianpopow** [comment] 2020-09-29 21:28
> Different decoders too? If not we have a memory allocation problem..

same with bmp, png and jpg decoder

**Comment by lofcz** [comment] 2020-09-30 05:22
@brianpopow regarding jpeg decoder: there was an extra defect with jpeg images, the image was converted to a super low quality in addition to one half being blank. No green strips tho.

**Comment by brianpopow** [comment] 2020-09-30 06:12
@lofcz yes something is different with the jpeg decoder. Its also defect even without Mutate. Looks like this:

![jpg_defect](https://user-images.githubusercontent.com/38701097/94649269-98935400-02f4-11eb-8c09-0c296ef4ebfc.jpg)

**Comment by tredition** [comment] 2020-09-30 06:48
Good to see I'm not the only one. I have a similar problem with cropping.
The following stuff is implemented in a web api project which works fine on my local machine. But when I deploy this to an Azure App Service, cropping leads to broken images. This happens since .NET 5 RC-1.

Code:

```
var image = Image.Load<Rgba32>(inputFilename);
image.Mutate(m => m.Crop(new Rectangle(left, top, width, height)));
image.Save(outputFilename);
```

Some PNG images still work fine, but JPG images of any size are broken. You could take any dimensions for cropping, it doesn't matter.

Original image:
![2017-06-24-u-bahn-rave-27](https://user-images.githubusercontent.com/50625823/94651530-e14d0c00-02f8-11eb-9282-e142a451476d.jpg)

Want to crop this area:
![image](https://user-images.githubusercontent.com/50625823/94651652-178a8b80-02f9-11eb-9b5d-3c6d7870c996.png)

Leads to this result:
![image](https://user-images.githubusercontent.com/50625823/94651708-325d0000-02f9-11eb-8ab4-a55189e49dd3.png)

Larger view:
![image](https://user-images.githubusercontent.com/50625823/94651776-4b65b100-02f9-11eb-9db5-5f43efde3f89.png)

**Comment by JimBobSquarePants** [comment] 2020-09-30 07:15
We're going to need to get issues raised upstream in the dotnet repo. They've changed something which is affecting us.

**Comment by klogeaage** [comment] 2020-09-30 07:23
Might I suggest this issue is renamed to something like ".Net 5.0 RC-1 breaks ImageSharp" ?

**Comment by JimBobSquarePants** [comment] 2020-09-30 14:30
@brianpopow I just updated your branch to include all the proper .NET5 build targets and updated some test dependencies. I have all tests passing on .NET5 locally. Can you please confirm in your docker instance (_I haven't a clue how to do that_)?

**Comment by tannergooding** [comment] 2020-09-30 16:38
Just commenting so I can get notifications on this. We'd like to have a tracking issue in dotnet/runtime if this does turn out to be a runtime related issue.

I'm also happy to help investigate further if required.

**Comment by tannergooding** [comment] 2020-09-30 18:35
@JimBobSquarePants, as an FYI we've logged a tracking issue, https://github.com/dotnet/runtime/issues/42912, as this is something we would classify as blocking-release if it is indeed an issue in dotnet/runtime.

Let us know if we can help with root causing or investigating it further. As we get closer to shipping, the window to get fixes in narrows and so we'd like to try and assist however possible to ensure this gets resolved quickly 😄

**Comment by JimBobSquarePants** [comment] 2020-09-30 18:44
Thanks @tannergooding really appreciate your help here!

**Comment by tocsoft** [comment] 2020-09-30 19:02
@brianpopow / @klogeaage I have attempted to create a standalone reproduction of the bug at https://github.com/tocsoft/Net5CorruptingImageSharp but I don't seem to be able to cause the issues you both have been seeing could I ask if you could attempt to run the code in repo and see if the outputs. I can't tell if its just my machine doesn't suffer from the issue or my tests are flawed.

**Comment by tocsoft** [comment] 2020-09-30 19:04
My reproduction isn't aiming at making it easy for us to debug at this stage its so that, if we can reproduce it consistently with only memory/.net version constants changing, we can raise an issue in against the runtime.

**Comment by klogeaage** [comment] 2020-09-30 19:45
@tocsoft, I have now installed Docker (which is new to me), cloned your repo and successfully run your PowerShell script. Unfortunately, the output looks perfectly good, so no reproduction of the issue ☹
Just to re-iterate, I only see the issue when deploying a release configuration to an Azure App Service from Visual Studio 2019 with a self-contained .Net 5 RC-1 runtime being installed. And only when the App Service is rather limited in memory. Is there anyway we can use that exact setup to recreate the issue?
A new version of VS2019 has just been released, just for the heck of it, I'll see if that makes any difference.

**Comment by tocsoft** [comment] 2020-09-30 20:48
@klogeaage Thanks for trying that.. sounds like I've not set up the test correctly I'll keep working see if I can get local repeatable reproduction.
Hoping @brianpopow might end up having an idea on what I've done wrong seeing as he seemed to have managed to reproduce the issue locally/in docker before.

**Comment by tannergooding** [comment] 2020-09-30 21:33
Is this only reproing on Windows or has anyone tried on Linux yet?

**Comment by tannergooding** [comment] 2020-09-30 23:39
So far I haven't been able to repro.

The test project I made is a simple console app using `<PackageReference Include="SixLabors.ImageSharp" Version="1.0.2-alpha.0.9" />` (latest nightly) on `net5.0` using the public RC1 from `https://get.dot.net` and the repro code from: https://github.com/SixLabors/ImageSharp/tree/bp/Issue1356docker

It is being run on a Windows 10 x64 Pro Hyper-V machine with 6 cores and 512MB of RAM (I don't think I can get Windows much lower than that >.>).

Will try to build the latest ImageSharp locally next and will try docker after that.

**Comment by klogeaage** [comment] 2020-10-01 11:53
> Is this only reproing on Windows or has anyone tried on Linux yet?

I just tried deploying to a Linux based App Service in Azure and there the issue reproduces in almost identical manner, including it goes away with plenty of memory. 

And it turns out I can run my test environment at less than half price on Linux, so I'm contemplating switching permanently. But I digress  :-)

**Comment by brianpopow** [comment] 2020-10-01 12:47
> Is this only reproing on Windows or has anyone tried on Linux yet?

@tannergooding so far i have only seen this issue on linux, but the one who started this thread said it fails on **windows server 2016 datacenter 10.0.14393, net5 rc1**, too.

@lofcz could you please confirm that it is indeed failing on windows?

**Comment by brianpopow** [comment] 2020-10-01 13:23
> @brianpopow I just updated your branch to include all the proper .NET5 build targets and updated some test dependencies. I have all tests passing on .NET5 locally. Can you please confirm in your docker instance (_I haven't a clue how to do that_)?

@JimBobSquarePants lots of tests are failing in docker: **Failed:   293, Passed:  5299, Skipped:     5, Total:  5597**
And that is not even all tests executed. If you want the log files, let me know in slack, its to much to post here.

If you want to execute it in docker just use the following in the root directory of ImageSharp:

```
docker-compose build
docker-compose up
```

This will run the Issue1356 project and the output will be written to the host system in *docker_output* folder (in ImageSharp root directory)

If you want to run the tests just uncomment the last two lines in the dockerfile.

@tocsoft i will look into your reproduction code now.

**Comment by brianpopow** [comment] 2020-10-01 13:41
> @klogeaage Thanks for trying that.. sounds like I've not set up the test correctly I'll keep working see if I can get local repeatable reproduction.
> Hoping @brianpopow might end up having an idea on what I've done wrong seeing as he seemed to have managed to reproduce the issue locally/in docker before.

@tocsoft I have tested your reproduction and i can reproduce it with it. Both net5 results (low and high memory fail) and look like this:

![garden](https://user-images.githubusercontent.com/38701097/94816706-7ab11680-03fc-11eb-9d74-7b4a4e6be9a1.jpg)

![small](https://user-images.githubusercontent.com/38701097/94816711-7be24380-03fc-11eb-9a00-8d90115a3d28.jpg)

net31 results are looking fine.

**Comment by tocsoft** [comment] 2020-10-01 14:50
ok some more stuff for everyone looks like it might have nothing to do with memory at this stage but in fact its looks like it more related to number of CPUs/core available

The difference between the 2 skus mentioned by @klogeaage is not just memory size but also CPU constraints. Based on the memory looks like we are talking about a 'B1' scale machine and a 'P2V2'  the difference on those machines is not just memory by a move from approx. 1 cpu to something more like 4. 

Only way i've managed to repo it at the moment is run docker using the hyper-v backend with the hyper-v vm itself being constrained (not just the running container as my test cases above where trying to do).

**Comment by tocsoft** [comment] 2020-10-01 14:52
@tannergooding the guide toward the face it seems to be a CPU count issue rather than a memory constraint issue might help in your verification/tests too.

**Comment by tannergooding** [comment] 2020-10-01 15:11
Ah, yeah. I can repro instantly by setting Hyper-V to use 1-core, rather than 6 (even with multiple gigs of memory).

**Comment by tocsoft** [comment] 2020-10-01 15:41
looking like its the decoder that triggering the regression, if I generate a hash of pixel data after decoding be before any other process is ran then the hashes differ on 1cpu and are the same on 2 cpus

**Comment by klogeaage** [comment] 2020-10-01 16:28
> The difference between the 2 skus mentioned by @klogeaage is not just memory size but also CPU constraints. Based on the memory looks like we are talking about a 'B1' scale machine and a 'P2V2' the difference on those machines is not just memory by a move from approx. 1 cpu to something more like 4.

Yes, indeed, you have deducted it absolutely right. So glad we are narrowing this down to something meaningful.

**Comment by tannergooding** [comment] 2020-10-01 16:55
We've got some people on the runtime team that are going to look further: https://github.com/dotnet/runtime/issues/42912

For future reference, we don't strictly need a minimal repro on dotnet/runtime for an issue to be opened.
We'd much rather get an issue opened than not see it all, especially when we are this late in the release cycle 😄 

This might be a more complex runtime bug, in which case finding a minimal repro might be difficult or impossible.

**Comment by tocsoft** [comment] 2020-10-01 17:06
@tannergooding Oh thanks for raising that I was planning to it myself one I had reduced it a little more.

**Comment by tredition** [comment] 2020-10-02 06:18
A short info: It seems that it doesn't have to do anything with cropping, resizing etc. Just tried out: Simply open a jpg image and save it -> Broken in an Azure App Service (Windows):

```
            var image = Image.Load<Rgba32>(filename);
            image.Save(filename);
```

**Comment by tocsoft** [comment] 2020-10-02 07:23
it definitely the JPEG decoder that's failing I've updated my reproduction repo to verify that's the case. https://github.com/tocsoft/Net5CorruptingImageSharp

**Comment by brianpopow** [comment] 2020-10-05 04:19
good news: It looks like with .Net 5.0 RC-2 this issue will be fixed!

**Comment by Sergio0694** [comment] 2020-10-13 18:21
@JimBobSquarePants .NET 5 RC2 is out! 🚀🚀🚀

**Comment by brianpopow** [comment] 2020-10-13 19:23
I have tested this issue again with RC2 and can confirm the issue is gone. I will close the issue now. 

Thanks to all who helped tracking down this issue!

**Closed by brianpopow** 2020-10-13 19:23 UTC
Labels: area:build, upstream-issue
