### ISSUE TITLE
Maintain Xamarin iOS support by keeping the library "AOT-proof"

### ISSUE THREAD

**Issue by antonfirsov** [SixLabors/ImageSharp#946] opened 2019-07-14 10:25 UTC
## Description
Xamarin iOS users need to be able to "seed" open-generic library API-s with the help of [AotCompilerTools](https://github.com/SixLabors/ImageSharp/blob/master/src/ImageSharp/Advanced/AotCompilerTools.cs), otherwise it will lead to [runtime exceptions](https://github.com/SixLabors/ImageSharp/issues/776#issuecomment-510424553) on that platform.

**Related:**  #767, #785, #776, #800

## Problems
Currently we are struggling to maintain this feature because of the following reasons:
- There is no one in the core team having experience with Xamarin iOS or any other AOT platform.
- We don't have any regression tests for this, we never know when a change breaks the "AOT-proofness" of an existing API
- We have introduced a massive change with #904, which will most likely break AOT & Xamarin iOS for many existing API-s in RC1. I have defined a point in epic #907 to investigate this, however in practice it turned out that I hardly have the resources to do so during this summer. (Neither I think @JimBobSquarePants can make it.) Therefore it will most likely not happen for RC1.

## Conclusion
With our current prioritites and resources, the only way to maintain this feature is community support. If you can provide any help (add missing AOT seeds, or fix regressions), feel free to open a Pull Request!

#### Long term solution
If someone could define a mono AOT test configuration for appveyor, that would be ace.

/CC @vicfergar  @davilovick  @gameleon-dev @Lapinou42 @dmanning23 @swoolcock

**EDIT**
**PS:** Could someone do a favor and chack the latest MyGet dev builds from on Xamarin iOS? (JPEG, PNG, Resize, Quantization etc.)

**Comment by dmanning23** [comment] 2019-07-15 00:52
Cool, super appreciate the work yall have been putting into ImageSharp. I have some downtime this week and can take a look at the iOS build.

**Comment by JimBobSquarePants** [comment] 2019-07-16 04:26
@dmanning23 That would be absolutely amazing if you can, thank you very much!

**Comment by dmanning23** [comment] 2019-07-19 20:04
Opened a pull-request with a few changes to fix ImageSharp on iOS. I've verified with these changes that it works for jpg, gif, and image resizing.
I also rolled up some changes I've had in mind for the https://github.com/SixLabors/ImageSharp/issues/800 ticket. I've verified that the AoTCompilerTools.Seed methods never actually have to be called, that code just needs to be present for the AoT compiler to pick it up.

Since these AoT/JIT errors only pop up at runtime, and only on physical iOS devices (doesn't occur on simulator!), it'll be extremely difficult to come up with a CI solution to detect them before they pop up.  I've started asking around if any other Xamarin developers know how to detect & fix these issues preemptively.

**Comment by gameleon-dev** [comment] 2019-07-19 20:21
@dmanning23 
> I've verified with these changes that it works for jpg, gif, and image resizing.

Would these changes also fix issues with PNG images? PNG was the format giving the most JIT/AOT issues in beta-0006.

**Comment by antonfirsov** [comment] 2019-07-19 21:02
> Would these changes also fix issues with PNG images? PNG was the format giving the most iOS based JIT/AOT issues in beta-0006.

I don't think so.

Suggested follow-up step:
- Run `Image.Load(...)` for all the test images [within our test suite](https://github.com/SixLabors/ImageSharp/tree/master/tests/Images/Input), inside a mono AOT or a Xamarin iOS app.
- Collect the failing ones into a checklist of missing seeds we can address.

**Comment by dmanning23** [comment] 2019-07-19 23:06
Ok, I can take a look at .png images also.

**Comment by gameleon-dev** [comment] 2019-07-20 08:18
Mostly loading from PNG bytes. I haven't been able to properly test encoding to PNG yet in an iOS environment.

I can consistently reproduce the following error by loading png image bytes using `Image.Load(pngbytes)`: 

```
Unhandled managed exception: Attempting to JIT compile method 'SixLabors.ImageSharp.Formats.Png.PngScanlineProcessor:ProcessRgbaScanline<SixLabors.ImageSharp.PixelFormats.Rgba32> (SixLabors.ImageSharp.Configuration,SixLabors.ImageSharp.Formats.Png.PngHeader&,System.ReadOnlySpan`1<byte>,System.Span`1<SixLabors.ImageSharp.PixelFormats.Rgba32>,int,int)' while running in aot-only mode. See https://docs.microsoft.com/xamarin/ios/internals/limitations for more information.
 (System.ExecutionEngineException)
  at SixLabors.ImageSharp.Formats.Png.PngDecoderCore.ProcessDefilteredScanline[TPixel] (System.ReadOnlySpan`1[T] defilteredScanline, SixLabors.ImageSharp.ImageFrame`1[TPixel] pixels, SixLabors.ImageSharp.Formats.Png.PngMetaData pngMetaData) [0x00135] in <7430a37e6bca4100b1763856ff8f7867>:0 
  at SixLabors.ImageSharp.Formats.Png.PngDecoderCore.DecodePixelData[TPixel] (System.IO.Stream compressedStream, SixLabors.ImageSharp.ImageFrame`1[TPixel] image, SixLabor
s.ImageSharp.Formats.Png.PngMetaData pngMetaData) [0x000e5] in <7430a37e6bca4100b1763856ff8f7867>:0 
  at SixLabors.ImageSharp.Formats.Png.PngDecoderCore.ReadScanlines[TPixel] (System.IO.Stream dataStream, SixLabors.ImageSharp.ImageFrame`1[TPixel] image, SixLabors.ImageSharp.Formats.Png.PngMetaData pngMetaData) [0x00018] in <7430a37e6bca4100b1763856ff8f7867>:0 
  at SixLabors.ImageSharp.Formats.Png.PngDecoderCore.Decode[TPixel] (System.IO.Stream stream) [0x00171] in <7430a37e6bca4100b1763856ff8f7867>:0 
  at SixLabors.ImageSharp.Formats.Png.PngDecoder.Decode[TPixel] (SixLabors.ImageSharp.Configuration configuration, System.IO.Stream stream) [0x00008] in <7430a37e6bca4100b1763856ff8f7867>:0 
  at SixLabors.ImageSharp.Image.Decode[TPixel] (System.IO.Stream stream, SixLabors.ImageSharp.Configuration config) [0x00015] in <7430a37e6bca4100b1763856ff8f7867>:0 
  at SixLabors.ImageSharp.Image+<>c__DisplayClass55_0`1[TPixel].<Load>b__0 (System.IO.Stream s) [0x00000] in <7430a37e6bca4100b1763856ff8f7867>:0 
  at SixLa
bors.ImageSharp.Image.WithSeekableStream[T] (SixLabors.ImageSharp.Configuration config, System.IO.Stream stream, System.Func`2[T,TResult] action) [0x0002b] in <7430a37e6bca4100b1763856ff8f7867>:0 
  at SixLabors.ImageSharp.Image.Load[TPixel] (SixLabors.ImageSharp.Configuration config, System.IO.Stream stream, SixLabors.ImageSharp.Formats.IImageFormat& format) [0x00022] in <7430a37e6bca4100b1763856ff8f7867>:0 
  at SixLabors.ImageSharp.Image.Load[TPixel] (SixLabors.ImageSharp.Configuration config, System.IO.Stream stream) [0x00000] in <7430a37e6bca4100b1763856ff8f7867>:0 
  at SixLabors.ImageSharp.Image.Load[TPixel] (SixLabors.ImageSharp.Configuration config, System.Byte[] data) [0x00007] in <7430a37e6bca4100b1763856ff8f7867>:0 
  at SixLabors.ImageSharp.Image.Load (System.Byte[] data) [0x00005] in <7430a37e6bca4100b1763856ff8f7867>:0 
```

A similar error occurs when loading a png image from a stream.

**Comment by antonfirsov** [comment] 2019-07-26 23:16
Someone has to call [all the PNG scanline decoder methods](https://github.com/SixLabors/ImageSharp/blob/master/src/ImageSharp/Formats/Png/PngDecoderCore.cs#L649) from `AotCompilerTools`.

I expect similar issues with gif, and probably even certain jpegs.

The following steps do not require any knowledge related of our codebase, and it would be really helpful if someone could do them:
1. Upload [our whole test image suite](https://github.com/SixLabors/ImageSharp/tree/master/tests/Images/Input) to an iOS device.
2. Run [this code](https://gist.github.com/antonfirsov/08f73989c9ce1861e1381ca67673b1b1) from inside a Xamarin.iOS app. (If running into something like OutOfMemoryException: just delete the giant jpegs.)
3. Send back `Report.txt`

This will help getting a nice overview about how bad the situation is. I want to avoid doing the discussion overhead image-by-image.

**Comment by dmanning23** [comment] 2019-07-27 04:24
Awesome, I will have some extra time next week and will create a quick iOS app with those images & code.

**Comment by dmanning23** [comment] 2019-08-07 07:26
Ok wrote a quick&dirty iOS app that loads all the images in the test suite, and didn't run into any AoT/JIT errors. Whatever error it was hitting must have been fixed in https://github.com/SixLabors/ImageSharp/pull/949

@gameleon-dev If you want to send me the specific .png I can double check that it will work going forward.

https://github.com/dmanning23/ImageSharpTest.iOS

**Comment by JimBobSquarePants** [comment] 2019-08-07 14:55
@dmanning23 Legend! 👑

**Comment by gameleon-dev** [comment] 2019-08-07 20:00
@dmanning23 Thank you so much!

If it's any help testing, the images I used that generated the error were iOS screenshots. (Taken with the default [iOS screenshot feature](https://support.apple.com/en-us/HT200289))

I've attached one of them to this comment.

Attachment: [IMG_7829](https://user-images.githubusercontent.com/5390147/62653769-9175ed80-b95e-11e9-9a8d-348b071cb714.PNG)

**Comment by dmanning23** [comment] 2019-08-07 22:26
You should be good to go, I was able to load the attached image:
```
2019-08-07 17:24:44.794 ImageSharpTest.iOS[2745:131288] Testing Content/62653769-9175ed80-b95e-11e9-9a8d-348b071cb714.png
2019-08-07 17:24:45.439 ImageSharpTest.iOS[2745:131288]    ... SUCCESS!
```

**Comment by omatrot** [comment] 2020-05-02 07:45
@antonfirsov Following #1183 I have the same problem with RC1.

**Comment by brianpopow** [comment] 2020-05-02 11:01
> @antonfirsov Following #1183 I have the same problem with RC1.

@omatrot  could you please provide the image which is failing for you? I have tried to reproduce this with mono as described here [mono aot](https://www.mono-project.com/docs/advanced/aot/), but all the png work fine with RC1. My guess is you really need to run that on an iOS device to get this error.

**Comment by omatrot** [comment] 2020-05-02 11:58
@brianpopow Here it is.
![profile_pic](https://user-images.githubusercontent.com/4366356/80863472-e68c2900-8c7c-11ea-81f3-2ac98944bc5e.png)

**Comment by greg-dickie** [comment] 2020-06-02 22:17
@antonfirsov I'm getting this error when compiling my Xamarin Forms/iOS app after adding the ImageSharp NuGet package: error MT3001: Could not AOT the assembly '/Users/gregdickie/Library/Caches/Xamarin/mtbs/builds/Forms.Mobile.iOS/3888efad18065936af5713c2f604b75c/obj/iPhone/Debug/mtouch-cache/3-Build/SixLabors.ImageSharp.dll'.

Any ideas what could be causing this?

**Comment by antonfirsov** [comment] 2020-06-03 14:22
@greg-dickie you have a compile-time error, any chance it's rather related #1183?

Since it's unrelated to the "seeding" concerns addressed by this issue, I suggest to move the discussion to our [gitter channel](https://gitter.im/ImageSharp/General), it has better visibility there. Do you have more info in your compiler output?

**Comment by unamed000** [comment] 2020-08-25 12:24
I tried 1.0.1 version today and it seem to be an issue when rotating gif images.
The weird problem is it's only occur on an heavy gif, if i just use a small size gif, it doesn't throw this error.
And it's only the case when build in an ios device. Not on simulator.
 Here is the stack trace:

`2020-08-25 19:23:50.967 AulaNative.iOS[729:179997] Unhandled managed exception: Attempting to JIT compile method 'void SixLabors.ImageSharp.Formats.Gif.GifDecoderCore:ReadFrameColors<SixLabors.ImageSharp.PixelFormats.Rgba32> (SixLabors.ImageSharp.Image`1<SixLabors.ImageSharp.PixelFormats.Rgba32>&,SixLabors.ImageSharp.ImageFrame`1<SixLabors.ImageSharp.PixelFormats.Rgba32>&,SixLabors.ImageSharp.Memory.Buffer2D`1<byte>,System.ReadOnlySpan`1<SixLabors.ImageSharp.PixelFormats.Rgb24>,SixLabors.ImageSharp.Formats.Gif.GifImageDescriptor&)' while running in aot-only mode. See https://docs.microsoft.com/xamarin/ios/internals/limitations for more information.
 (System.ExecutionEngineException)
  at SixLabors.ImageSharp.Formats.Gif.GifDecoderCore.ReadFrame[TPixel] (SixLabors.ImageSharp.Image`1[TPixel]& image, SixLabors.ImageSharp.ImageFrame`1[TPixel]& previousFrame) [0x00096] in <b0936bd831134aeda01f0a913657f33a>:0 
  at SixLabors.ImageSharp.Formats.Gif.GifDecoderCore.Decode[TPixel] (SixLabors.ImageSharp.IO.BufferedReadStream stream, System.Threading.CancellationToken cancellationToken) [0x0002d] in <b0936bd831134aeda01f0a913657f33a>:0 
  at SixLabors.ImageSharp.Formats.ImageDecoderUtilities.Decode[TPixel] (SixLabors.ImageSharp.Formats.IImageDecoderInternals decoder, SixLabors.ImageSharp.Configuration configuration, System.IO.Stream stream, System.Func`3[T1,T2,TResult] largeImageExceptionFactory) [0x00008] in <b0936bd831134aeda01f0a913657f33a>:0 
  at SixLabors.ImageSharp.Formats.ImageDecoderUtilities.Decode[TPixel] (SixLabors.ImageSharp.Formats.IImageDecoderInternals decoder, SixLabors.ImageSharp.Configuration configuration, System.IO.Stream stream) [0x00000] in <b0936bd831134aeda01f0a913657f33a>:0 
  at SixLabors.ImageSharp.Formats.Gif.GifDecoder.Decode[TPixel] (SixLabors.ImageSharp.Configuration configuration, System.IO.Stream stream) [0x00007] in <b0936bd831134aeda01f0a913657f33a>:0 
  at SixLabors.ImageSharp.Formats.Gif.GifDecoder.Decode (SixLabors.ImageSharp.Configuration configuration, System.IO.Stream stream) [0x00000] in <b0936bd831134aeda01f0a913657f33a>:0 
  at SixLabors.ImageSharp.Image.Decode (System.IO.Stream stream, SixLabors.ImageSharp.Configuration config) [0x00015] in <b0936bd831134aeda01f0a913657f33a>:0 
  at SixLabors.ImageSharp.Image+<>c__DisplayClass137_0.<Load>b__0 (System.IO.Stream s) [0x00000] in <b0936bd831134aeda01f0a913657f33a>:0 
  at SixLabors.ImageSharp.Image.WithSeekableStream[T] (SixLabors.ImageSharp.Configuration configuration, System.IO.Stream stream, System.Func`2[T,TResult] action) [0x00041] in <b0936bd831134aeda01f0a913657f33a>:0 
  at SixLabors.ImageSharp.Image.Load (SixLabors.ImageSharp.Configuration configuration, System.IO.Stream stream, SixLabors.ImageSharp.Formats.IImageFormat& format) [0x0000d] in <b0936bd831134aeda01f0a913657f33a>:0 
  at SixLabors.ImageSharp.Image.Load (SixLabors.ImageSharp.Configuration configuration, System.IO.Stream stream) [0x00000] in <b0936bd831134aeda01f0a913657f33a>:0 
  at SixLabors.ImageSharp.Image.Load (System.IO.Stream stream) [0x00005] in <b0936bd831134aeda01f0a913657f33a>:0 `

**Comment by antonfirsov** [comment] 2020-08-25 13:16
> The weird problem is it's only occur on an heavy gif.

@unamed000 this sounds crazy, Xamarin AOT is really weird if this is true. What happens if decoding a large gif is preceeded by decoding a small one?

As far as I understand, gif decoding is [properly seeded](https://github.com/SixLabors/ImageSharp/blob/master/src/ImageSharp/Advanced/AotCompilerTools.cs#L95).

**Comment by unamed000** [comment] 2020-08-25 13:23
@antonfirsov i will try that tomorrow and let you know.
 
But i tried to clone the project and embedded the ImageSharp directly into my project. And i did some Seeding of my own for Decode method of GifDecoderCore. This time, it does not throw JIT error anymore, it just dies silently without throwing anything? Which is also the case for the large gif.

**Comment by JimBobSquarePants** [comment] 2020-08-25 13:29
Thanks @unamed000 that stacktrace is really useful.

I don't think rotation is the issue here the first line indicates the method. Why it only happens with large gifs (how big btw?) I don't know. 

``` c#
void SixLabors.ImageSharp.Formats.Gif.GifDecoderCore:ReadFrameColors<SixLabors.ImageSharp.PixelFormats.Rgba32> (SixLabors.ImageSharp.Image`1<SixLabors.ImageSharp.PixelFormats.Rgba32>&,SixLabors.ImageSharp.ImageFrame`1<SixLabors.ImageSharp.PixelFormats.Rgba32>&,SixLabors.ImageSharp.Memory.Buffer2D`1<byte>,System.ReadOnlySpan`1<SixLabors.ImageSharp.PixelFormats.Rgb24>,SixLabors.ImageSharp.Formats.Gif.GifImageDescriptor&)
```

We've not done any work on AOT compilation in a long time because we simply don't have the tools and resources to do any investigation into potential issues, we rely purely on individual cases raised here.

@antonfirsov I can see looking at the code that our current `Seed<TPixel>()` methods are going to fail decoding early due to the input stream being `null`. I wonder if that affects the compilers ability to see the internal method calls?

Perhaps we should reverse the process and encode then decode a static byte array representing pixel data?

**Comment by unamed000** [comment] 2020-08-25 13:34
@JimBobSquarePants 
Yes, it does not relate anything to the rotate but in the Image.Load method only.
I tried that on an iPhone 8, which is fairly strong (bot flagship but its pretty ok), and i tried with a gif image around 4 megabytes and 2 megabytes before (both crashes with this same issue). Then i tried it with a 25kb and 100kb, these are not crashing.

**Comment by JimBobSquarePants** [comment] 2020-08-25 13:37
Sorry, I meant unencoded dimensions not file size.

Any help would be really useful, thanks! I can experiment with my seed idea (if everyone thinks it is sound) and get you to test is when you are able.

**Comment by antonfirsov** [comment] 2020-08-25 19:27
@JimBobSquarePants I like the idea.

@unamed000 any chance you can build the library from source, and try if the experiment works out?

**Comment by unamed000** [comment] 2020-08-26 03:08
@antonfirsov  yes, if you put in a branch, with some changes, i can try it out. I tried your idea today about uploading the small gif before uploading a large gif, the issue is still there.

@JimBobSquarePants Here are the 2 gif that i used to upload
![EC9BF060-FCB8-4B11-B7CD-FE43B696AEF6](https://user-images.githubusercontent.com/10647722/91250767-042d5300-e784-11ea-927d-1a94904867b2.gif)
![gif](https://user-images.githubusercontent.com/10647722/91250596-a00a8f00-e783-11ea-93ea-3670074273f0.gif)

**Comment by JimBobSquarePants** [comment] 2020-08-26 14:18
@unamed000 Can you please try building from source from this branch [js/aot-experiments](https://github.com/SixLabors/ImageSharp/tree/d00e3a9c592ad1ecf9f148366e39f4fb27a4a3e7)

I'm hoping the reference to `Configuration.Default` is enough to trigger the linker to preserve the relevant code since each codec is explicitly referenced in the construction of the default instance. If not' I'll explicitly reference the individual formats and codecs.

**Comment by unamed000** [comment] 2020-08-28 09:35
Hi @JimBobSquarePants 

It's not working, still the same stacktrace and error with the same line

**Comment by JimBobSquarePants** [comment] 2020-08-28 12:21
> It's not working, still the same stacktrace and error with the same line

I'm at a loss then....

Am I right in saying you can tell the linker to ignore the SixLabors binaries?

**Comment by unamed000** [comment] 2020-08-31 03:45
There is a an attribute that we can tell the linker to ignore a class as far as i know which is:
`[Preserve (AllMembers = true)]`

But i'm not really so sure about this though.

**Comment by JimBobSquarePants** [comment] 2020-09-02 14:42
You're ahead of me then. I've only briefly looked at the documentation. I don't do any application development.

**Comment by unamed000** [comment] 2020-09-03 07:58
After trying to disable line by line. I figured out which line is causing this:
It was actually this in ReadFrameColors method. The Rgb32.FromRgb24 method
![image](https://user-images.githubusercontent.com/10647722/92087603-e4d29d80-edf5-11ea-98de-cfd83e6ac260.png)

But i've no idea how to solve this

**Comment by antonfirsov** [comment] 2020-09-03 09:59
@unamed000 can you try what happens if you alter the implementation of `Rgba32.FromRgb24` ?

**Variant 1**
```C#
[MethodImpl(InliningOptions.ShortMethod)]
public void FromRgb24(Rgb24 source)
{
    this.R = source.R;
    this.G = source.G;
    this.B = source.B;
    this.A = byte.MaxValue;
}
```

**Variant 2** (No inlining)
```C#
public void FromRgb24(Rgb24 source)
{
    this.R = source.R;
    this.G = source.G;
    this.B = source.B;
    this.A = byte.MaxValue;
}
```

**Comment by JimBobSquarePants** [comment] 2020-09-03 10:32
I might have to dig out the Raspberry Pi again if we change that.

Perhaps adding implementation calls for all of the `IPixel` methods to `AotCompilerTools` would be better. They're missing currently.

**Comment by unamed000** [comment] 2020-09-03 11:51
@antonfirsov 
I tried that already, for removing the InliningOptions and not.
The result is InliningOptions does not change anything. It's just my work around that will be affected.

**Comment by antonfirsov** [comment] 2020-09-03 13:22
@JimBobSquarePants the difference between the "small" and "large" gifs might be actually a difference in `transFlag` here:
https://github.com/SixLabors/ImageSharp/blob/521fae35a14c7953f720a094d24b59b2f7d98555/src/ImageSharp/Formats/Gif/GifDecoderCore.cs#L485-L508

Does this make sense?
If this is true, the AOT compiler might probably fail to properly compile one of the paths.

It's probably worth to try seeding `FromRgb24` and similar calls in [`Seed<TPixel>`](https://github.com/SixLabors/ImageSharp/blob/c9e4d0550454577dbdd38ff3557bab1d0982e259/src/ImageSharp/Advanced/AotCompilerTools.cs#L81):
```C#
TPixel pixel = default;
pixel.FromRgb24(default);
```
@unamed000 can you try if adding this changes anything? (Probably in combination with other hacks.)

**Comment by antonfirsov** [comment] 2020-09-03 13:24
> Also, any idea why a high dimension gif file is breaking on iOS device? Could it be because it's using too much memory?

@unamed000 in your previous comment you stated:
> I try to resize the second image into 50x50 but it's still the same issue, same like it was not the dimensions after all?

Can you try if it works with the resized version with any of the hacks?

**Comment by unamed000** [comment] 2020-09-03 13:39
Hi @antonfirsov , i'll try your suggestion tomorrow

> Can you try if it works with the resized version with any of the hacks?

I actually tried that before, here is the summary for what i did

|                         | Small Image                                     | Big Image                                       |
|-------------------------|-------------------------------------------------|-------------------------------------------------|
| With my hack (SetupAot) | Able to Load                                    | Crash without yielding any stacktrace           |
| Without my hack         | JIT Compiler stacktrace (ReadFromColors method) | JIT Compiler stack trace(ReadFromColors method) |

So i think with my current hack, i'm able to get rid of the AOT issue, though the crash without stacktrace could be something else, it could be either:
- Something loop forever inside (this is the case i usually see when Xamarin does not yield any stacktrace)
- Too high memory usage.

**Comment by antonfirsov** [comment] 2020-09-03 14:43
> Too high memory usage.

What if you upscale a different gif? (One that did noes not produce this issue originally)
If it also hangs, can you incrementally find a size where it starts to hang? (or maybe slow down very noticeably)

**Comment by unamed000** [comment] 2020-09-04 03:53
> What if you upscale a different gif? (One that did noes not produce this issue originally)

I've resize the gif to like your suggestion and here is the result:
250x250 gif, it's working fine
![contho250x250](https://user-images.githubusercontent.com/10647722/92197623-83193e80-ee9c-11ea-918b-5042e59e09a3.gif)

400x400 gif, it's crashing without stacktrace
![contho400x400](https://user-images.githubusercontent.com/10647722/92197633-88768900-ee9c-11ea-8d4d-6afcee785779.gif)

Though these gif are very light, it crashes when only 400x400 pixels, so i don't think that could be high memory usage?

> It's probably worth to try seeding FromRgb24 and similar calls in Seed<TPixel>:
Tried that as well, somehow not working, it's only work if i seed directly for Rgba32.FromRgb24

> the difference between the "small" and "large" gifs might be actually a difference in transFlag here:
The transFlag are the same for both images since the width and height ratio is the same.

**Comment by antonfirsov** [comment] 2020-09-04 10:12
So far it looks like the crash is a completely separate problem. Does it happen on emulator as well?

Can you help us by filing a new GitHub issue for it (with templates filled) so we can track it?

**Comment by JimBobSquarePants** [comment] 2020-09-07 11:26
> Tried that as well, somehow not working, it's only work if i seed directly for Rgba32.FromRgb24

Just to clarify @unamed000 you are saying the following did not work when added to `AotCompilerTools`?

```c#
TPixel pixel = default;

Rgb24 rgb24 = default;
pixel.FromRgb24(rgb24);
```

@antonfirsov if that is the case then we should migrate to using T4 for generating the tools. Messier to extend but if it's the only thing that works we have little choice.

**Comment by unamed000** [comment] 2020-09-08 03:47
@JimBobSquarePants 
yes, i tried that before and i didn't workout.
But could you give me a little of explanation why we need to seed these? Even though i copied the entire code into my project seem like i need to seed them as well (I don't have much knowledge about these "seeding" things)

**Comment by JimBobSquarePants** [comment] 2020-09-08 07:58
@unamed000 I just updated my branch as I realized I made a mistake in the loader code and was calling the `Rgba32` version only. I would pull the latest from that branch and build/reference from that source code.

The reason we seed the code is to attempt to ensure the AOT compiler doesn't try to delete code branches it incorrectly thinks are not being used. By explicitly calling troublesome methods we try to get the compiler to recognize their use. 

You shouldn't have to copy the code to your system I wouldn't think.

**Comment by unamed000** [comment] 2020-09-09 08:49
@JimBobSquarePants would you indicate which branch you did the update?

**Comment by JimBobSquarePants** [comment] 2020-09-09 08:51
https://github.com/SixLabors/ImageSharp/tree/js/aot-experiments

**Comment by JimBobSquarePants** [comment] 2020-09-17 10:28
@unamed000 How did you get on building from the source in the branch?

**Comment by JimBobSquarePants** [comment] 2020-10-13 16:18
We need someone to raise an issue upstream here for us to track. We can't fix issues with the AOT compiler.

**Comment by UltraNamahage** [comment] 2021-03-08 07:49
I had a similar problem with Unity Android IL2CPP, but I found a solution.
Xamarin iOS and Unity Android IL2CPP both work with Mono, so I think you can solve it the same way.

According to the [Unity manual](https://docs.unity3d.com/2021.1/Documentation/Manual/ScriptingRestrictions.html), you need to write a specific code to make a particular generic method work.

This should probably cache all interface methods that have generic methods.
[For example, this part.](https://github.com/SixLabors/ImageSharp/blob/a1784a67bf492b1b02e99655a39aa5e5acf81988/src/ImageSharp/Processing/Processors/ICloningImageProcessor.cs#L24)

I wanted to shrink a large PNG image, so I created the following code.
```
/// <summary>
/// Because it calls an internal class, it needs to be placed inside the ImageSharp project.
/// </summary>
static class UnityAoT<TPixel> where TPixel : unmanaged, IPixel<TPixel>
{
    /// <summary>
    /// call from <see cref="SixLabors.ImageSharp.Advanced.AotCompilerTools.Seed{TPixel}"/>
    /// </summary>
    internal static void UnitySeed()
    {
        AotCompileImageProcessor();
        AotCompileResampler();
        AotCompileEncoder();
    }
    private static void AotCompileEncoder()
    {
        default(PngEncoderCore).Encode<TPixel>(default, default, default);
    }
    private static void AotCompileImageProcessor()
    {
        AotCompilerPixelSpecifics<ResizeProcessor>();
    }
    private static void AotCompilerPixelSpecifics<TProc>()
        where TProc : class, ICloningImageProcessor
    {
        default(TProc).CreatePixelSpecificCloningProcessor<TPixel>(default, default, default);
        default(TProc).CreatePixelSpecificProcessor<TPixel>(default, default, default);
    }
    private static void AotCompileResampler()
    {
        AotCompileResamplers<BicubicResampler>();
    }
    private static void AotCompileResamplers<TResampler>()
        where TResampler : struct, IResampler
    {
        // TODO : Methodize it.
        default(ResizeProcessor<TPixel>).ApplyTransform<TResampler>(default);
        default(TResampler).ApplyTransform(default(ResizeProcessor<TPixel>));
    }
}
```
This is working fine, but doesn't allow me to do anything other than shrink.
I think we need to cache more methods to do all the processing.

**Closed** 2021-03-15 11:50 UTC
Labels: API, area:aot, help needed, upstream-issue
