### ISSUE TITLE
When padding (using resize) a large image an exception is generated.

### ISSUE THREAD

**Issue by metscore** [SixLabors/ImageSharp#774] opened 2018-11-09 16:02 UTC
### Prerequisites
- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of ImageSharp
- [x] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
I've written a small MapTiler program and for testing purposes I've used a fairly large image from [ESO](https://www.eso.org/public/images/eso1119a/).
The image is 16017 x 16017 pixels, 72 dpi,  24 bit depth and is in jpg format.

Originally I've created the code

```
Image<Rgba32> processingImage = null;
processingImage = Image.Load<Rgba32>(this.myFileName);
processingImage.Mutate(x => x.Pad(16384, 16384));

```
and it works very nicely, the image is padded and centered and all is good !
However I did not want the image centered, but rather top left, so I replaced the code with 

```
Image<Rgba32> processingImage = null;
processingImage = Image.Load<Rgba32>(this.myFileName);
processingImage.Mutate(x => x.Resize(new ResizeOptions { Mode = ResizeMode.BoxPad, Position = AnchorPositionMode.TopLeft, Size = new Size(16384, 16384) }));
```

but then get the exception

`{SixLabors.ImageSharp.ImageProcessingException: An error occurred when processing the image using ResizeProcessor`1. See the inner exception for more detail. ---> System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.Parameter name: minimumLength   at System.Buffers.ConfigurableArrayPool`1.Rent(Int32 minimumLength)   at SixLabors.Memory.ArrayPoolMemoryAllocator.Allocate[T](Int32 length, AllocationOptions options)   at SixLabors.ImageSharp.Memory.MemoryAllocatorExtensions.Allocate2D[T](MemoryAllocator memoryAllocator, Int32 width, Int32 height, AllocationOptions options)   at SixLabors.ImageSharp.Processing.Processors.Transforms.ResizeProcessor`1.OnFrameApply(ImageFrame`1 source, ImageFrame`1 destination, Rectangle sourceRectangle, Configuration configuration)   at SixLabors.ImageSharp.Processing.Processors.CloningImageProcessor`1.CloneAndApply(Image`1 source, Rectangle sourceRectangle)   --- End of inner exception stack trace`

I'm probably missing some key element that I'm supposed to do, but can't figure out what and why. If someone has a clue what I'm doing wrong, please give me some guidance. 
(I've tried with the same image in png format, but I get the same error message.  However, if I use smaller images such as 9195 x 5616 it works fine and no exception is generated)

Thank you very much for the nice ImageSharp package ! I really like it !

Keep up the good work !
King regards,
Magnus

### Steps to Reproduce
To reproduce, load the [image](https://cdn.eso.org/images/large/eso1119a.jpg) to disk.
Use code 

```
Image<Rgba32> processingImage = null;
processingImage = Image.Load<Rgba32>("eso1119a.jpg");
processingImage.Mutate(x => x.Resize(new ResizeOptions { Mode = ResizeMode.BoxPad, Position = AnchorPositionMode.TopLeft, Size = new Size(16384, 16384) }));

```
### System Configuration
Windows 10.
Visual Studio 2017 (15.8.9)
Project .Net Core 2.1
SixLabours.ImageSharp 1.0.0-beta0005

**Comment by antonfirsov** [comment] 2018-11-09 18:37
@metscore this issue seems to be a duplicate of #636.
There is already a discussion analyzing root causes. Please let us know about your thoughts/ideas on that thread!

**Closed by antonfirsov** 2018-11-09 18:37 UTC

**Comment by metscore** [comment] 2018-11-10 14:46
@antonfirsov Sorry, for some strange reason I completely missed #636.
