### ISSUE TITLE
Text run incorrectly applied inclusively to final letter when End points to final letter of text string

### ISSUE THREAD

**Issue by jez9999** [SixLabors/ImageSharp#2846] opened 2024-12-10 19:27 UTC
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have verified that I am running the latest version of ImageSharp
- [X] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [X] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### ImageSharp version

3.1.6

### Other ImageSharp packages and versions

SixLabors.ImageSharp.Drawing 2.1.4

### Environment (Operating system, version and so on)

Windows 10

### .NET Framework version

.NET 9

### Description

When using `TextRuns` to apply different formatting to different parts of text in `DrawText`, ImageSharp appears to incorrectly include the final character of the input text in a text run if the text run's `End` points to the final letter of the text string (it is supposed to be exclusive, so the letter pointed to should *not* be formatted by that text run).  A minimal reproduction is given below.  It's a C# console program with classes `FontManager` and `Program`.

### Steps to Reproduce

**FontManager.cs**
```
using SixLabors.Fonts;

namespace TextRunTest;

internal class FontManager {
    public FontManager() {
        _allFontsCollection = new FontCollection();
        _allFontsCollection.AddSystemFonts();
    }

    private readonly FontCollection _allFontsCollection;
    private readonly Dictionary<(string FontName, float FontSize, FontStyle FontStyle), Font> _cachedFonts = [];

    public Font GetFont(string fontName, float fontSize, FontStyle fontStyle) {
        var key = (fontName, fontSize, fontStyle);

        if (!_cachedFonts.ContainsKey(key)) {
            _cachedFonts[key] = _allFontsCollection.Get(fontName).CreateFont(fontSize, fontStyle);
        }
        return _cachedFonts[key];
    }
}
```

**Program.cs**
```
using System.Numerics;
using SixLabors.ImageSharp;
using SixLabors.ImageSharp.Drawing.Processing;
using SixLabors.ImageSharp.PixelFormats;
using SixLabors.ImageSharp.Processing;
using SixLabors.Fonts;

namespace TextRunTest;

internal class Program {
    static void Main(string[] args) {
        Console.WriteLine("Rendering test images...");

        var fontManager = new FontManager();

        Image imgTest = new Image<Rgba32>(300, 200, Color.White);
        imgTest.Mutate(x =>
            x.DrawText(
                new RichTextOptions(fontManager.GetFont("Arial", 80, FontStyle.Regular)) {
                    Origin = new Vector2(50, 20),
                    TextRuns = [
                        new() {
                            Font = fontManager.GetFont("Arial", 80, FontStyle.Italic),
                            Start = 1,
                            End = 4
                        }
                    ]
                },
                "linell",
                Color.Black
            )
        );
        imgTest.SaveAsPng("c:/development/diff/testImg1.png");
        // ^ correct, italicized: linell
        //                         ---

        Image imgTest2 = new Image<Rgba32>(300, 200, Color.White);
        imgTest2.Mutate(x =>
            x.DrawText(
                new RichTextOptions(fontManager.GetFont("Arial", 80, FontStyle.Regular)) {
                    Origin = new Vector2(50, 20),
                    TextRuns = [
                        new() {
                            Font = fontManager.GetFont("Arial", 80, FontStyle.Italic),
                            Start = 1,
                            End = 5
                        }
                    ]
                },
                "linell",
                Color.Black
            )
        );
        imgTest2.SaveAsPng("c:/development/diff/testImg2.png");
        // ^ incorrect, italicized: linell
        //                           -----

        Console.WriteLine("Done.");
    }
}
```

### Images

![testImg1](https://github.com/user-attachments/assets/5c8da28b-5442-4ba4-b8a1-2a5344f97755)
![testImg2](https://github.com/user-attachments/assets/8d53b299-cfbe-4b84-a6c4-e59406f3bea8)

**Comment by tocsoft** [comment] 2024-12-10 19:57
I believe this was fixed as part of https://github.com/SixLabors/Fonts/pull/420 which was release as part of [SixLabors.Fonts V2.0.6 release](https://github.com/SixLabors/Fonts/releases/tag/v2.0.6)

@jez9999 please can you try updating/adding a reference to [SixLabors.Fonts V2.0.6 nuget package](https://www.nuget.org/packages/SixLabors.Fonts/2.0.6)

**Comment by jez9999** [comment] 2024-12-10 20:04
Yeah, that fixes it.  Shouldn't that get pulled in by the latest version of `SixLabors.ImageSharp.Drawing`?

**Comment by JimBobSquarePants** [comment] 2024-12-10 22:23
Because that would require a new Drawing release which I haven’t had the opportunity to look at. 

Can you please ensure you use the correct repository for issues. This is a duplicate of https://github.com/SixLabors/Fonts/issues/412

**Closed by JimBobSquarePants** 2024-12-10 22:23 UTC
Labels: needs triage
