### ISSUE TITLE
ArgumentOutOfRangeException thrown when drawing text

### ISSUE THREAD

**Issue by fantasyzhjk** [SixLabors/ImageSharp#2114] opened 2022-05-11 09:28 UTC
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have verified that I am running the latest version of ImageSharp
- [X] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [X] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### ImageSharp version

2.1.1

### Other ImageSharp packages and versions

Fonts: 1.0.0-beta16 Drawing: 1.0.0-beta14

### Environment (Operating system, version and so on)

Windows 11

### .NET Framework version

.NET Core 6

### Description

Error drawing text containing '/' at the beginning or end
```cs
Unhandled exception. System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at System.Collections.Generic.List`1.get_Item(Int32 index)
   at SixLabors.Fonts.GlyphSubstitutionCollection.GetGlyphShapingData(Int32 index)
   at SixLabors.Fonts.Tables.AdvancedTypographic.Shapers.DefaultShaper.AssignFeatures(IGlyphShapingCollection collection, Int32 index, Int32 count)
   at SixLabors.Fonts.Tables.AdvancedTypographic.GSubTable.ApplySubstitution(FontMetrics fontMetrics, GlyphSubstitutionCollection collection, KerningMode kerningMode)
   at SixLabors.Fonts.StreamFontMetrics.ApplySubstitution(GlyphSubstitutionCollection collection, KerningMode kerningMode)
   at SixLabors.Fonts.FileFontMetrics.ApplySubstitution(GlyphSubstitutionCollection collection, KerningMode kerningMode)
   at SixLabors.Fonts.TextLayout.DoFontRun(ReadOnlySpan`1 text, TextOptions options, FontMetrics fontMetrics, BidiRun[] bidiRuns, Dictionary`2 bidiMap, GlyphSubstitutionCollection substitutions, GlyphPositioningCollection positionings)
   at SixLabors.Fonts.TextLayout.ProcessText(ReadOnlySpan`1 text, TextOptions options)
   at SixLabors.Fonts.TextLayout.GenerateLayout(ReadOnlySpan`1 text, TextOptions options)
   at SixLabors.Fonts.TextRenderer.RenderText(ReadOnlySpan`1 text, TextOptions options)
   at SixLabors.Fonts.TextRenderer.RenderText(String text, TextOptions options)
   at SixLabors.ImageSharp.Drawing.Processing.Processors.Text.DrawTextProcessor`1.BeforeImageApply()
   at SixLabors.ImageSharp.Processing.Processors.ImageProcessor`1.SixLabors.ImageSharp.Processing.Processors.IImageProcessor<TPixel>.Execute()
   at SixLabors.ImageSharp.Processing.DefaultImageProcessorContext`1.ApplyProcessor(IImageProcessor processor, Rectangle rectangle)
   at SixLabors.ImageSharp.Processing.DefaultImageProcessorContext`1.ApplyProcessor(IImageProcessor processor)
   at SixLabors.ImageSharp.Drawing.Processing.DrawTextExtensions.DrawText(IImageProcessingContext source, DrawingOptions drawingOptions, TextOptions textOptions, String text, IBrush brush, IPen pen)
   at SixLabors.ImageSharp.Drawing.Processing.DrawTextExtensions.DrawText(IImageProcessingContext source, TextOptions textOptions, String text, IBrush brush, IPen pen)
   at SixLabors.ImageSharp.Drawing.Processing.DrawTextExtensions.DrawText(IImageProcessingContext source, TextOptions textOptions, String text, Color color)
```

### Steps to Reproduce

```cs
var uiFont = SystemFonts.Get("Segoe UI");

using var img = new Image<Rgba32>(500, 500);
img.Mutate(x => x.Fill(Color.Black));

TextOptions textOptions = new(uiFont.CreateFont(128))
{
    Origin = Vector2.Zero,
};

img.Mutate(x => x.DrawText(textOptions, "/", Color.White));
```

**Comment by JimBobSquarePants** [comment] 2022-05-11 09:30
Wrong repository and also a duplicate of https://github.com/SixLabors/Fonts/issues/244

**Closed by JimBobSquarePants** 2022-05-11 09:30 UTC
Labels: needs triage
