### ISSUE TITLE
ImageSharp.ImageFormatException 'Too many coefficients 64 > 63

### ISSUE THREAD

**Issue by Meday7** [SixLabors/ImageSharp#309] opened 2017-08-24 09:18 UTC
### Description
I got next error when trying to handle specific image: 

> ImageSharp.ImageFormatException 'Too many coefficients 64 > 63

### Steps to Reproduce
Here is my code:
` using (var image = Image.Load(fileInfo.PhysicalPath))
                    {
                        image
                            .Resize(new Size(width, height))
                            .Save(path, new JpegEncoder()
                            {
                                Quality = quality
                            });
                    }
`

Here is my image: [https://yadi.sk/i/umUKZBd23MHWAm](url)
### System Configuration

- ImageSharp version: 1.0.0-alpha9-00182
- Environment (Operating system, version and so on): Windows 10, ubuntu
- .NET Framework version: .net core 1.1

**Comment by JimBobSquarePants** [comment] 2017-08-24 12:58
Fairly certain this is a duplicate. Did you check?

**Comment by JimBobSquarePants** [comment] 2017-08-25 03:58
Yup. Duplicate of #178 

Thanks for raising this though and thanks for the test image. This really helps us. 👍

**Closed** 2017-08-25 03:59 UTC
Labels: area:formats:jpeg, bug, duplicate
