### ISSUE TITLE
Docs not available in Brazil

### ISSUE THREAD

**Issue by AngeloSchulerPiletti** [SixLabors/ImageSharp#2834] opened 2024-10-30 22:01 UTC
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have verified that I am running the latest version of ImageSharp
- [X] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [X] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### ImageSharp version

N/A

### Other ImageSharp packages and versions

N/A

### Environment (Operating system, version and so on)

N/A

### .NET Framework version

N/A

### Description

Hello.

I noticed that I can't access the docs from Brazil. When I turned on the VPN from US it worked.

https://docs.sixlabors.com/

### Steps to Reproduce

Try connecting to a VPN in Brazil and then access the docs https://docs.sixlabors.com/

**Comment by johnseto** [comment] 2024-11-01 22:32
No problem accessing the https://docs.sixlabors.com.
I used NordVPN to connect to Sao Paolo. I confirmed the location was correct by looking up on https://whatismyipaddress.com.

**Comment by JimBobSquarePants** [comment] 2024-11-19 03:56
I'm going to close this as it appears to work now.

**Comment by stefannikolei** [comment] 2024-12-11 09:39
Seems to be solved since 8 days. Can you confirm @AngeloSchulerPiletti

**Comment by AngeloSchulerPiletti** [comment] 2024-12-11 10:33
Yes, it's working again!

**Closed** 2024-12-11 11:47 UTC
Labels: upstream-issue
