### ISSUE TITLE
Cannot load assembly System.IO.Compression on Image.Load with Png file.

### ISSUE THREAD

**Issue by melenaos** [SixLabors/ImageSharp#287] opened 2017-08-01 09:50 UTC
### Prerequisites

- [X ] I have written a descriptive issue title
- [X ] I have verified that I am running the latest version of ImageSharp
- [ ] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [X ] I have searched [open](https://github.com/JimBobSquarePants/ImageSharp/issuess) and [closed](https://github.com/JimBobSquarePants/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
I have a NetStandard lib with ImageSharp installed and it's used from a Net.4.6.2 console app(used as webjob) and everytime I try to load a png using Image.Load() it thows an exception of FileNotFound 

### Exception
System.IO.FileNotFoundException: Could not load file or assembly 'System.IO.Compression, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' or one of its dependencies. The system cannot find the file specified.
File name: 'System.IO.Compression, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'
   at ImageSharp.Formats.PngDecoderCore.Decode[TPixel](Stream stream)
   at ImageSharp.Formats.PngDecoder.Decode[TPixel](Configuration configuration, Stream stream, IDecoderOptions options)
   at ImageSharp.Image.Decode[TPixel](Stream stream, IDecoderOptions options, Configuration config)
   at ImageSharp.Image.<>c__DisplayClass36_0`1.<Load>b__0(Stream s)
   at ImageSharp.Image.WithSeekableStream[T](Stream stream, Func`2 action)
   at ImageSharp.Image.Load[TPixel](Configuration config, Stream stream, IDecoderOptions options)
   at ReportFormat.Formater.ExcelFormater.<AddImages>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ReportFormat.Formater.ExcelFormater.<GenerateReportStream>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ReportFormat.ReportFormatGenerator.<GenerateReport>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Services.Process.ReportGenerationProcess.<ProcessAsync>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at xxx.Functions.<ProcessUserReport>d__0.MoveNext() in

**Comment by JimBobSquarePants** [comment] 2017-08-01 09:52
Duplicate of #184

**Closed by JimBobSquarePants** 2017-08-01 09:52 UTC
