### ISSUE TITLE
Regression in loading jpeg images from v1.0.4 to v2.0.0

### ISSUE THREAD

**Issue by darthmaule2** [SixLabors/ImageSharp#2057] opened 2022-03-10 11:58 UTC
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have verified that I am running the latest version of ImageSharp
- [X] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [X] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### ImageSharp version

2.0.0

### Other ImageSharp packages and versions

None

### Environment (Operating system, version and so on)

Windows 10 Enterprise 20H2, x64

### .NET Framework version

6.0

### Description

With ImageSharp v1.0.4 (and .NET 6.0), I could successfully load the attached images.

After upgrading to ImageSharp v2.0.0 (and .NET 6.0), the attached images throw either an InvalidImageContentException or a NullReferenceException, depending on the image. I've labeled them with the exception they throw.

### Steps to Reproduce

Run the following coding
```C#
Stream fs = fileSystem.File.OpenRead(file.FullName);
Image<Bgr24> image = Image.Load<Bgr24>(fs);
```

### Images

![InvalidImageContentException2](https://user-images.githubusercontent.com/5235630/157655914-54c65940-36cd-4b28-910b-c9967fbdc598.jpg)
![NullReferenceException](https://user-images.githubusercontent.com/5235630/157655917-50d8d0b5-e9e8-49e6-8326-e10503d43676.jpg)
![InvalidImageContentException1](https://user-images.githubusercontent.com/5235630/157655920-f6b0c7b5-82d5-40bb-a750-f102e90a2417.jpg)

**Comment by JimBobSquarePants** [comment] 2022-03-10 13:41
Thanks for the all info. Do you have a stacktrace at all?

**Comment by darthmaule2** [comment] 2022-03-10 14:26
**InvalidImageContentException:**
```
   at SixLabors.ImageSharp.Formats.Jpeg.JpegThrowHelper.ThrowInvalidImageContentException(String errorMessage)
   at SixLabors.ImageSharp.Formats.Jpeg.JpegDecoderCore.ProcessStartOfFrameMarker(BufferedReadStream stream, Int32 remaining, JpegFileMarker& frameMarker, Boolean metadataOnly)
   at SixLabors.ImageSharp.Formats.Jpeg.JpegDecoderCore.ParseStream(BufferedReadStream stream, HuffmanScanDecoder scanDecoder, CancellationToken cancellationToken)
   at SixLabors.ImageSharp.Formats.Jpeg.JpegDecoderCore.Decode[TPixel](BufferedReadStream stream, CancellationToken cancellationToken)
   at SixLabors.ImageSharp.Formats.ImageDecoderUtilities.Decode[TPixel](IImageDecoderInternals decoder, Configuration configuration, Stream stream, Func`3 largeImageExceptionFactory)
   at SixLabors.ImageSharp.Formats.ImageDecoderUtilities.Decode[TPixel](IImageDecoderInternals decoder, Configuration configuration, Stream stream)
   at SixLabors.ImageSharp.Formats.Jpeg.JpegDecoder.Decode[TPixel](Configuration configuration, Stream stream)
   at SixLabors.ImageSharp.Image.Decode[TPixel](Stream stream, Configuration config)
   at SixLabors.ImageSharp.Image.<>c__DisplayClass135_0`1.<Load>b__0(Stream s)
   at SixLabors.ImageSharp.Image.WithSeekableStream[T](Configuration configuration, Stream stream, Func`2 action)
   at SixLabors.ImageSharp.Image.Load[TPixel](Configuration configuration, Stream stream, IImageFormat& format)
   at SixLabors.ImageSharp.Image.Load[TPixel](Configuration configuration, Stream stream)
   at SixLabors.ImageSharp.Image.Load[TPixel](Stream stream)
   at Modules.FileManager.FileManagerViewModel.GenerateSingleThumbnail(IRviFile file, Boolean finalRetry) in C:\Users\210047453\source\repos\theia\sbc_sw\src\ExecUICore3\Modules.FileManager\FileManagerViewModel.cs:line 467
```
**NullReferenceException:**
```
   at SixLabors.ImageSharp.Formats.Jpeg.Components.Decoder.SpectralConverter`1.GetPixelBuffer(CancellationToken cancellationToken)
   at SixLabors.ImageSharp.Formats.Jpeg.JpegDecoderCore.Decode[TPixel](BufferedReadStream stream, CancellationToken cancellationToken)
   at SixLabors.ImageSharp.Formats.ImageDecoderUtilities.Decode[TPixel](IImageDecoderInternals decoder, Configuration configuration, Stream stream, Func`3 largeImageExceptionFactory)
   at SixLabors.ImageSharp.Formats.ImageDecoderUtilities.Decode[TPixel](IImageDecoderInternals decoder, Configuration configuration, Stream stream)
   at SixLabors.ImageSharp.Formats.Jpeg.JpegDecoder.Decode[TPixel](Configuration configuration, Stream stream)
   at SixLabors.ImageSharp.Image.Decode[TPixel](Stream stream, Configuration config)
   at SixLabors.ImageSharp.Image.<>c__DisplayClass135_0`1.<Load>b__0(Stream s)
   at SixLabors.ImageSharp.Image.WithSeekableStream[T](Configuration configuration, Stream stream, Func`2 action)
   at SixLabors.ImageSharp.Image.Load[TPixel](Configuration configuration, Stream stream, IImageFormat& format)
   at SixLabors.ImageSharp.Image.Load[TPixel](Configuration configuration, Stream stream)
   at SixLabors.ImageSharp.Image.Load[TPixel](Stream stream)
   at Modules.FileManager.FileManagerViewModel.GenerateSingleThumbnail(IRviFile file, Boolean finalRetry) in C:\Users\210047453\source\repos\theia\sbc_sw\src\ExecUICore3\Modules.FileManager\FileManagerViewModel.cs:line 467

**Comment by brianpopow** [comment] 2022-03-13 15:32
I believe all images linked in this thread suffer from the same issue with different symptoms. With #2058 merged, I believe the issue is fixed.

@darthmaule2  If you have time, could you verify this and try out our [nightly builds](https://www.myget.org/feed/sixlabors/package/nuget/SixLabors.ImageSharp)

**Comment by brianpopow** [comment] 2022-03-14 17:54
@darthmaule2 thanks for the confirmation, will close the issue then.

**Closed by brianpopow** 2022-03-14 17:54 UTC
Labels: bug, formats:jpeg
