### ISSUE TITLE
Dosen't support webp now

### ISSUE THREAD

**Issue by rocketRobin** [SixLabors/ImageSharp#522] opened 2018-04-10 05:59 UTC
What time this library could support webp? this image format is becoming popular every day. I need this support in my project! Basicly I at least need to get the width and height of an webp image, I need this feeture, thanks a lot!

**Comment by JimBobSquarePants** [comment] 2018-04-10 06:00
Duplicate of #121

**Closed by JimBobSquarePants** 2018-04-10 06:00 UTC
