### ISSUE TITLE
SixLabors create an invalid file after conversion 

### ISSUE THREAD

**Issue by sedjura** [SixLabors/ImageSharp#2300] opened 2022-11-30 10:24 UTC
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have verified that I am running the latest version of ImageSharp
- [X] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [X] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### ImageSharp version

3.0.0-alpha.0.65

### Other ImageSharp packages and versions

3.0.0-alpha.0.65

### Environment (Operating system, version and so on)

Windows\Linux

### .NET Framework version

6

### Description

For version 65 of nightly sixlabors package we've met issue with image conversion
We take original image from resources and convert it without options by sixlabors to jpg
Result image in brokenImageModel.jpg file can be opened in MS Paint but cannot be edited or saved properly
it can cause failures on s3 or cdn storages during upload with "File signature doesn't match" exception

### Steps to Reproduce

1) Run console application from https://github.com/sedjura/SixLaborsBrokenImage
or run code below
2) In application directory code will generate brokenImage.jpg
3) Open it with MS Paint and try to save
4) Paint will refuse to save it due to unknown error

```c#
using SixLaborsBrokenConversion.Properties;

namespace SixLaborsBrokenConversion;

/// <summary>
///     For version 65 of nightly sixlabors package we've met issue with image conversion
///     We take original image from resources and convert it without options by sixlabors to jpg
///     Result image in brokenImageModel.jpg file can be opened in MS Paint but cannot be
///     edited or saved properly
///     it can cause failures on s3 or cdn storages during upload with
///     "File signature doesn't match" exception
/// </summary>
internal class Program
{
    const string BrokenFilePath = @"./brokenImageModel.jpg";

    static async Task Main(string[] args)
    {
        //get fine image from project resources
        var sixLaborsImage = Image.Load(Resources.imageModel);

        using var ms = new MemoryStream();
        
        // fill ms stream with original image converted to sixlabors jpeg image
        await sixLaborsImage.SaveAsJpegAsync(ms, CancellationToken.None);

        // save image to file
        await using var fileStream = File.Create(BrokenFilePath);
        ms.Seek(0, SeekOrigin.Begin);
        await ms.CopyToAsync(fileStream);

        // try to open and save it with MS Paint
        // ???
        // Failure
    }
}
```

### Images

![imageModel](https://user-images.githubusercontent.com/11475983/204770525-f9de29a8-de50-49c5-9c26-ebcdf0c155f2.jpg)
![Без имени](https://user-images.githubusercontent.com/11475983/204771068-b6815aa5-d6bb-4159-9094-8efc42ef466d.png)

**Comment by tocsoft** [comment] 2022-11-30 12:46
could there be a rouge null byte in the header somewhere that causes paint to freak out... and could posibly be the cause on the s3 stream failing too when it reaches that byte?

**Comment by JimBobSquarePants** [comment] 2022-11-30 12:48
In the XMP chunk header? Yeah maybe. Odd that s3 would parse that far though.

**Comment by sedjura** [comment] 2022-11-30 13:05
Thanks a lot for a quick answer. 
Actually I tried setting XMP profile to null but error still shows up. After that I also set ExifProfile to null and everything worked.
For proper conversion I need to set both of them.
`        sixLaborsImage.Metadata.ExifProfile = null;
        sixLaborsImage.Metadata.XmpProfile = null;`

**Comment by JimBobSquarePants** [comment] 2022-11-30 14:32
That doesn’t reflect what I am seeing. EXIF works fine for me.

**Comment by br3aker** [comment] 2022-12-02 10:11
I'll take a look, something is very odd.

**Comment by br3aker** [comment] 2022-12-04 17:12
That's strange but ImageSharp write significantly less metadata than original image has:

1. APP1 EXIF metadata marker
```
// Original image
*** Marker: APP1 (xFFE1) ***
  OFFSET: 0x00000014
  Length          = 3288
  Identifier      = [Exif]
  Identifier TIFF = 0x[4D4D002A 00000008]
  Endian          = Motorola (big)
  TAG Mark x002A  = 0x002A

```

```
// Resaved by ImageSharp
*** Marker: APP1 (xFFE1) ***
  OFFSET: 0x00000014
  Length          = 968 <= no thumbnail here, probably
  Identifier      = [Exif]
  Identifier TIFF = 0x[49492A00 08000000]
  Endian          = Intel (little)
  TAG Mark x002A  = 0x002A
```

2. APP13 with IPTC blocks:
```
// Original image
*** Marker: APP13 (xFFED) ***
  OFFSET: 0x00000CEE
  Length          = 4462
  Identifier      = [Photoshop 3.0]
```

```
// Resaved by ImageSharp
*** Marker: APP13 (xFFED) ***
  OFFSET: 0x00001ED9
  Length          = 85 <= a lot less
  Identifier      = [Photoshop 3.0]
```

Well, deleting APP13 marker solves this issue, so actual EXIF metadata is **not** affected.
@sedjura if possible, can you please test given image with `sixLaborsImage.Metadata.IptcProfile = null;`?

As far as I know APP13 can be 'referenced' from APP1 segment, given that ImageSharp does truncate APP1 segment in this case - I suppose stated problem could be caused by breaking this reference. I debugged this image decoding and found out that APP13 marker is **not** fully decoded. I hadn't really checked any of the metadata-related code, is app13 photoshop metadata decoding fully supported?

Yet another interesting detail is that given image contains thumbnail in APP1 marker which ImageSharp currently doesn't support and doesn't write back which possibly could mess up APP13 marker.

**Comment by sedjura** [comment] 2022-12-05 08:03
@br3aker I tried set up null IPTC profile and everything works to me.

**Comment by br3aker** [comment] 2022-12-05 08:21
There's definately something wrong here, even though IPTC profile in APP13 segment from **re-encoded** image lost a lot of data - it is valid. No 'standard' metadata software reports any errors but Paint fails? That's strange. If anybody have access to Photoshop - please re-save given image re-encoded by ImageSharp and post resulting image here (so we can inspect whether IPTC metadata is resaved by PS), if everything works there - I'd suggest that there's a bug in Paint.

**Comment by sedjura** [comment] 2022-12-05 08:33
I created a thread in Paint.Net community, maybe there we will have an answer
https://forums.getpaint.net/topic/121422-cant-edit-and-save-jpg-image-in-paint-while-other-editors-works/

**Comment by br3aker** [comment] 2022-12-05 08:53
> I created a thread in Paint.Net community, maybe there we will have an answer https://forums.getpaint.net/topic/121422-cant-edit-and-save-jpg-image-in-paint-while-other-editors-works/

Wrong destination - Paint.NET and MS Paint are different things :P

**Comment by JimBobSquarePants** [comment] 2022-12-05 10:36
@br3aker thanks for taking a peek. In the zip I shared [above](https://github.com/SixLabors/ImageSharp/issues/2300#issuecomment-1332083699) there's actually version of the image resaved using several applications that could be useful for comparison.

**Comment by JimBobSquarePants** [comment] 2024-07-24 02:11
I'm going to close this. Following the link to the Paint.NET support channels it looks like everything but MS Paint is absolutely happy with the encoded image. That suggests the issue is with MS Paint.

**Closed by JimBobSquarePants** 2024-07-24 02:11 UTC
Labels: bug, hacktoberfest, help needed
