### ISSUE TITLE
Issue for load image in table cell in ver. 3.1.4

### ISSUE THREAD

**Issue by prizmasoftware** [SixLabors/ImageSharp#2757] opened 2024-06-25 23:42 UTC
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have verified that I am running the latest version of ImageSharp
- [X] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [X] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### ImageSharp version

3.1.4

### Other ImageSharp packages and versions

2.1.8

### Environment (Operating system, version and so on)

Windows 10, Visual Studio 2022, ASP.NET Core Blazor App, C#

### .NET Framework version

NET 8

### Description

When use code in C#, PDFSharpCore:

ImageSource.ImageSourceImpl = new ImageSharpImageSource<Rgba32>();
row.Cells[0].AddImage(ImageSource.FromFile(imagePath));

with ImageSharp 3.1.4 and run  with debug, show error:

Microsoft.AspNetCore.Components.Server.Circuits.RemoteRenderer[100]
      Unhandled exception rendering component: Method not found: 'SixLabors.ImageSharp.Image`1<!!0> SixLabors.ImageSharp.Image.Load(System.String, SixLabors.ImageSharp.Formats.IImageFormat ByRef)'.
      System.MissingMethodException: Method not found: 'SixLabors.ImageSharp.Image`1<!!0> SixLabors.ImageSharp.Image.Load(System.String, SixLabors.ImageSharp.Formats.IImageFormat ByRef)'.
         at PdfSharpCore.Utils.ImageSharpImageSource`1.FromFileImpl(String path, Nullable`1 quality)
         at MigraDocCore.DocumentObjectModel.MigraDoc.DocumentObjectModel.Shapes.ImageSource.FromFile(String path, Nullable`1 quality)
         at Hydrotek.Reports.RadniNalogReports.RadniNalogReport.TabelaNaslov(Document document) in D:\Moji Dokumenti\Visual_Studio_2022\Projects\WEB\ASP\Blazor\Hydrotek\Reports\RadniNalogReports\RadniNalogReport.cs:line 180
         at Hydrotek.Reports.RadniNalogReports.RadniNalogReport.PDF_nalog() in D:\Moji Dokumenti\Visual_Studio_2022\Projects\WEB\ASP\Blazor\Hydrotek\Reports\RadniNalogReports\RadniNalogReport.cs:line 82
         at Hydrotek.Pages.RadniNalog.Radni_nalog.PDF_nalog() in D:\Moji Dokumenti\Visual_Studio_2022\Projects\WEB\ASP\Blazor\Hydrotek\Pages\RadniNalog\Radni_nalog.razor:line 531
         at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
         at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)
fail: Microsoft.AspNetCore.Components.Server.Circuits.CircuitHost[111]

When downgrade to ver. 2.1.8, work fine.

### Steps to Reproduce

Use code

ImageSource.ImageSourceImpl = new ImageSharpImageSource<Rgba32>();
row.Cells[0].AddImage(ImageSource.FromFile(imagePath));

with ImageSharp 3.1.4

**Comment by antonfirsov** [comment] 2024-06-26 00:06
This is an issue with PdfSharpCore, they need to update their ImageSharp version.

Closing as duplicate of #2441.

**Closed by antonfirsov** 2024-06-26 00:06 UTC
Labels: needs triage
