### ISSUE TITLE
'' is an unsupported type

### ISSUE THREAD

**Issue by alexthekid07** [SixLabors/ImageSharp#1360] opened 2020-09-24 17:11 UTC
.NET Framework 4.7
ImageSharp version 1.0.1

This code worked fine in 1.0.0-beta0007 and I'm not 100% sure what's changed, and I didn't see anything too obvious in the release notes that would indicate why this is happening. I am basically just declaring a "default" image format and then letting the Image.Load() overwrite that with whatever it finds.

```
Dim outFormat As IImageFormat = JpegFormat.Instance
	Using img = SixLabors.ImageSharp.Image.Load(Of Rgba32)(imgBytes, format:=outFormat)
End Using
```

**Comment by antonfirsov** [comment] 2020-09-24 17:36
Duplicate of #1202 Please upvote that issue, and see the discussion there.

**Closed by antonfirsov** 2020-09-24 17:36 UTC
Labels: duplicate

**Comment by antonfirsov** [comment] 2020-09-24 21:36
@alexthekid07 can't you use the non-generic `Image` class [introduced in beta 7](https://sixlabors.com/blog/beta-7/)? Do you really need to work with `Rgba32` for your use-case?

**Comment by alexthekid07** [comment] 2020-09-24 22:28
@antonfirsov You're absolutely right, not specifying Rgba32 fixes it. I don't really have any specific need for that, I had just had Rgba32 left over from previous versions.
