### ISSUE TITLE
Access Violation in 2.1, works fine in 1.04

### ISSUE THREAD

**Issue by alex-jitbit** [SixLabors/ImageSharp#2075] opened 2022-03-25 19:52 UTC
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have verified that I am running the latest version of ImageSharp
- [X] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [X] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### ImageSharp version

2.1.0

### Other ImageSharp packages and versions

none

### Environment (Operating system, version and so on)

Windows 2016

### .NET Framework version

6.0

### Description

We have an ASP.NET 6 app that uses ImageSharp 2.1 to resize images and create thumbnails (and that's it) for UGC. Several times a day our app crashes with this error:

```
Application: w3wp.exe
CoreCLR Version: 6.0.322.12309
.NET Version: 6.0.3
Description: The process was terminated due to an internal error in the .NET Runtime at IP 00007FF932A2A5A9 (00007FF932940000) with exit code 80131506.
```

It's very simple code. Some images throw this uncatchable error, which crashes our entire process.

Reverting back to 1.0.4 seems to help.

### Steps to Reproduce

Unfortunately I'm unable to reliably tell which images caused this, since it's a busy app with millions of HTTP requests. Also I had no time to create process dumps or anything, But I did narrow this down to ImageSharp - reverting nuget from 2.1 to 1.0.4 fixed the issue immediately. So I thought you should know.

PS. Also, posting this is to help someone who's going to google for a solution desperately

**Comment by JimBobSquarePants** [comment] 2022-03-25 20:53
Thanks @alex-jitbit for raising this.

However, without either a stack trace, dump or image we’re absolutely powerless to do anything about it. You’ll need to provide means to replicate the issue or submit a patch.

**Comment by alex-jitbit** [comment] 2022-03-25 22:33
@JimBobSquarePants 100% understand. I will try to set up automated crash-dump saving, and then let it run on 2.1 for a while. If I won't be able to provide more details feel free to close.

**Comment by JimBobSquarePants** [comment] 2022-03-26 01:47
Thanks. We definitely won’t be closing this issue. It’s top priority to avoid memory access violations.

**Comment by JimBobSquarePants** [comment] 2022-03-26 11:30
This may or may not be related but I have noticed we're missing a sanitation check here.

https://github.com/SixLabors/ImageSharp/blob/136cc143bba2fca255328751dd4580e4f8d413c3/src/ImageSharp/Formats/Jpeg/JpegDecoderCore.cs#L723-L734

We really should be checking for a valid length before reading despite how rare this should be.

```c#
if (ProfileResolver.IsProfile(this.temp, ProfileResolver.XmpMarker.Slice(0, ExifMarkerLength)))
{
    const int remainingXmpMarkerBytes = XmpMarkerLength - ExifMarkerLength;
    if (remaining < remainingXmpMarkerBytes || this.IgnoreMetadata)
    {
        // Skip the application header length.
        stream.Skip(remaining);
        return;
    }

    stream.Read(this.temp, ExifMarkerLength, remainingXmpMarkerBytes);
```

**Comment by alex-jitbit** [comment] 2022-03-26 16:30
@JimBobSquarePants thanks! Will try my best to dig some more debug info. I completely understand. 

JFYI, this is the code we use, like I said it's very basic

```csharp
using (Image srcBmp = Image.Load(imgData)) //"imgData" is a MemoryStream
{
	//omitted some custom code that does not use ImageSharp (calculating target dimensions)
	//...
	
	srcBmp.Mutate(x => x.Resize(newWidth, newHeight));
	
	//sometimes we use this instead of the above
	srcBmp.Mutate(x => x.Resize(new ResizeOptions { Mode = ResizeMode.Pad, Position = AnchorPositionMode.Center, Size = new Size(newWidth, newHeight), Sampler = KnownResamplers.NearestNeighbor }));

	using (var resultMs = new MemoryStream())
	{
		srcBmp.Save(resultMs, IsJpeg(imgData) ? new PngEncoder() : new JpegEncoder());
		//"IsJpeg" is our custom function that uses "magic numbers" to tell JPG from PNG
	}
}
```

**Comment by tocsoft** [comment] 2022-03-26 21:01
@alex-jitbit  unrelated to the bug reported but thought you would like to know but there is an overload of `Image.Load(imgData, out IImageFormat imageFormat)` that returns the format of the image loaded, saves you having to process the `imgData` stream twice as we have already done exactly that during load.  Also there is an overload/extension method on `Image` for saving that takes in an `IImageFormat` so you can call `srcBmp.Save(resultMs, imageFormat);` to save in the same format as the source image and avoid create a new encoder instance on each call. (at the very least you want to make them singletons, there is no need to create a new one every image).

**Comment by JimBobSquarePants** [comment] 2022-04-04 08:18
@alex-jitbit any update on means of replicating? We’re blocked from any further development of the libraries until we get this sorted.

**Comment by alex-jitbit** [comment] 2022-04-04 18:41
@JimBobSquarePants no, sorry, I was prohibited form setting up the automated crash dumps on production and can't replicate this on staging or local dev machine. I completely understand this issue is useless without STR, so feel free to close

**Comment by JimBobSquarePants** [comment] 2022-04-04 22:20
Not even a try… catch around the relevant code to identify a problematic image? You don’t need a process dump.

**Comment by alex-jitbit** [comment] 2022-04-05 09:59
@JimBobSquarePants we do have a try-catch around it, but no exception is thrown.

**Comment by br3aker** [comment] 2022-04-05 15:39
@alex-jitbit corrupted state exceptions are not caught by try-catch by default, 'access violation' is one of them. Unfortunately, dotnet6 dropped support of the CSE exception handling but you can use this event: [`AppDomain.UnhandledException`](https://docs.microsoft.com/en-us/dotnet/api/system.appdomain.unhandledexception?view=net-6.0).

Problem is that process crash can be caused by various exceptions, so it's better to confirm exact exception type before watching for potential access violations.

**Comment by JimBobSquarePants** [comment] 2022-04-13 00:34
@alex-jitbit Did you get permission to ad @br3aker suggested capture approach?

**Closed** 2022-04-20 03:49 UTC
Labels: needs triage

**Comment by JimBobSquarePants** [comment] 2022-04-20 05:24
@alex-jitbit We've pushed some significant decoder sanitation code to main which is now in build [`2.1.1-alpha.0.4`](https://www.myget.org/feed/sixlabors/package/nuget/SixLabors.ImageSharp) which should fix any memory access issues.

It would be great if you could test this release for us before we ship a release to NuGet

**Comment by JimBobSquarePants** [comment] 2022-05-31 15:16
It’s more than a little disappointing that you took so long to get back to us. I’m not sure what you expect us to be able to do.

**Comment by alex-jitbit** [comment] 2022-05-31 16:08
@JimBobSquarePants Sorry about that. It's OK I'll just stick to v1 then. JFYI it appears it's not related to some particular image, but to a high-load scenario with ~15k requests per minute. Must be the new pooling/pool trimming mechanisms.

**Comment by antonfirsov** [comment] 2022-06-01 16:43
@alex-jitbit you can't stay on 1.0 forever, so it would be great to give another try to figure this out :)

Is 2 days the actual up-time before your high-load service dies? What does your service do? (=what ImageSharp API-s are called).

**Comment by alex-jitbit** [comment] 2022-06-02 08:56
@JimBobSquarePants I will add an AppDomain.UnhandledException handler and try to gather more info and get back to you.

@antonfirsov [here](https://github.com/SixLabors/ImageSharp/issues/2075#issuecomment-1079727642) is the code we use. Our app a is CRUD business app with file attachments, that simply generates thumbnails for UGC images before storing those on CDN.

**Comment by alex-jitbit** [comment] 2023-01-17 22:08
I just realized that my app is published as `ReadyToRun` so it might be connected to #2148

**Comment by JimBobSquarePants** [comment] 2023-01-21 05:24
Have you tried .NET 7?

**Comment by alex-jitbit** [comment] 2023-03-05 14:18
@JimBobSquarePants unfortunately, no because it's STS, while most of enterprise-grade customers have policies that require LTS releases only

**Comment by antonfirsov** [comment] 2023-03-07 16:13
@alex-jitbit any further information you could share upon the fact that the load is ~15k RPM? (Typical formats, image sizes, hardware configuration etc.) Any chance you can create a crash dump?
