### ISSUE TITLE
Image.DetectFormat vs Image.DetectFormatAsync: package 2.1.3 leaves stream at last read position for async call

### ISSUE THREAD

**Issue by fluffynuts** [SixLabors/ImageSharp#2368] opened 2023-02-23 10:55 UTC
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have verified that I am running the latest version of ImageSharp
- [X] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [X] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### ImageSharp version

2.1.3

### Other ImageSharp packages and versions

n/a

### Environment (Operating system, version and so on)

Windows 11

### .NET Framework version

7.0

### Description

In the release package (2.1.3), Image.DetectFormat behaves differently from Image.DetectFormatAsync in that the latter leaves the stream being read at the last-read position instead of 0 (for the case of a stream which can seek).

This appears to be fixed upstream though, as the following test passes in my fork of ImageSharp:
```csharp
[Fact]
public async Task AsyncAndSyncMethods_ShouldReturnStreamPositionToZero()
{
    var stream = new MemoryStream(ActualImageBytes.Length);
    stream.Write(ActualImageBytes, 0, ActualImageBytes.Length);
    stream.Seek(0, SeekOrigin.Begin);

    Assert.Equal(0, stream.Position);
    Image.DetectFormat(stream);
    Assert.Equal(0, stream.Position);
    await Image.DetectFormatAsync(stream);
    Assert.Equal(0, stream.Position);
}
```

Translating to NUnit and running in my project targeting 2.1.3, this fails on the last assertion as the stream is left at the end position.

The fix would seem to be to release a new package with the current code, as the current code is working fine here.

### Steps to Reproduce

Run the test above against 2.1.3 and again against `main`

**Comment by JimBobSquarePants** [comment] 2023-02-23 10:56
Can you please try the V3 alphas for this. I've reworked that area recently and believe I have ironed out any kinks.

**Comment by fluffynuts** [comment] 2023-02-23 13:53
not so much - I forked to provide a fix, and couldn't get it to fail, then did a comparison of the decompiled code from the package against what I was working with in the fork to realise that it had already been fixed, just not released 😅

**Comment by JimBobSquarePants** [comment] 2023-02-24 13:07
OK. I'll close this then if the issue is not in v3. Thanks

**Closed by JimBobSquarePants** 2023-02-24 13:07 UTC
Labels: needs triage
